//>>built
define("dojox/json/ref","dojo/_base/array dojo/_base/json dojo/_base/kernel dojo/_base/lang dojo/date/stamp dojox".split(" "),function(H,p,I,A,D,v){A.getObject("json",!0,v);return v.json.ref={resolveJson:function(e,g){function m(a,E,f,b,n,h,F){var c,u,d;f=q in a?a[q]:f;if(q in a||void 0!==f&&b)f=(t+f).replace(r,"$2$3");b=h||a;if(void 0!==f){v&&(a.__id=f);if(g.schemas&&!(a instanceof Array)&&(d=f.match(/^(.+\/)[^\.\[]*$/)))n=g.schemas[d[1]];if(k[f]&&a instanceof Array==k[f]instanceof Array)b=k[f],
delete b.$ref,delete b._loadObject,u=!0;else if(d=n&&n.prototype)w.prototype=d,b=new w;k[f]=b;x&&(x[f]=g.time)}for(;n;){if(d=n.properties)for(c in a){var y=d[c];y&&("date-time"==y.format&&"string"==typeof a[c])&&(a[c]=D.fromISOString(a[c]))}n=n["extends"]}n=a.length;for(c in a){if(c==n)break;if(a.hasOwnProperty(c)){d=a[c];if("object"==typeof d&&d&&!(d instanceof Date)&&"__parent"!=c){l=d[p]||z&&d[q];if(a!=s&&(!l||!d.__parent))d.__parent=F?F:b;if(l)if(delete a[c],h=l.toString().replace(/(#)([^\.\[])/,
"$1.$2").match(/(^([^\[]*\/)?[^#\.\[]*)#?([\.\[].*)?/),k[(t+l).replace(r,"$2$3")]?l=k[(t+l).replace(r,"$2$3")]:(l="$"==h[1]||"this"==h[1]||""===h[1]?e:k[(t+h[1]).replace(r,"$2$3")])&&h[3]&&h[3].replace(/(\[([^\]]+)\])|(\.?([^\.\[]+))/g,function(a,b,c,d,f){l=l&&l[c?c.replace(/[\"\'\\]/,""):f]}),l)d=l;else{if(!E){var G;G||s.push(b);G=!0;d=m(d,!1,d[p],!0,y);d._loadObject=g.loader}}else E||(d=m(d,s==a,void 0===f?void 0:C(f,c),!1,y,b!=a&&"object"==typeof b[c]&&b[c],a))}a[c]=d;if(b!=a&&!b.__isDirty&&(h=
b[c],b[c]=d,u&&d!==h&&!b._loadObject&&!("_"==c.charAt(0)&&"_"==c.charAt(1))&&"$ref"!=c&&!(d instanceof Date&&h instanceof Date&&d.getTime()==h.getTime())&&!("function"==typeof d&&"function"==typeof h&&d.toString()==h.toString())&&k.onUpdate))k.onUpdate(b,c,h,d)}}if(u&&(q in a||b instanceof Array))for(c in b){if(!b.__isDirty&&b.hasOwnProperty(c)&&!a.hasOwnProperty(c)&&!("_"==c.charAt(0)&&"_"==c.charAt(1))&&!(b instanceof Array&&isNaN(c))){if(k.onUpdate&&"_loadObject"!=c&&"_idAttr"!=c)k.onUpdate(b,
c,b[c],void 0);for(delete b[c];b instanceof Array&&b.length&&void 0===b[b.length-1];)b.length--}}else if(k.onLoad)k.onLoad(b);return b}g=g||{};var q=g.idAttribute||"id",p=this.refAttribute,z=g.idAsRef,t=g.idPrefix||"",v=g.assignAbsoluteIds,k=g.index||{},x=g.timeStamps,l,s=[],r=/^(.*\/)?(\w+:\/\/)|[^\/\.]+\/\.\.\/|^.*\/(\/)/,C=this._addProp,w=function(){};e&&"object"==typeof e&&(e=m(e,!1,g.defaultId,!0),m(s,!1));return e},fromJson:function(e,g){var m;try{m=eval("("+e+")")}catch(p){throw new SyntaxError("Invalid JSON string: "+
p.message+" parsing: "+e);}return m?this.resolveJson(m,g):m},toJson:function(e,g,m,q,B){function z(){var a=(C++).toString();return s.hasOwnProperty(a)?z():a}function t(a,e,f){if("object"==typeof a&&a){if(a instanceof Date)return'"'+D.toISOString(a,{zulu:!0})+'"';var b=a.__id;if(b){if("#"!=e&&(A&&!b.match(/#/)||l[b]))return f=b,"#"!=b.charAt(0)&&(f=a.__clientId==b?"cid:"+b:b.substring(0,m.length)==m?b.substring(m.length):b),a={},a[x]=f,p.toJson(a,g);e=b}else r?a instanceof Array||(e=z(),a.__id=e,s[e]=
a):(a.__id=e,s[e]=a);l[e]=a;f=f||"";var n=g?f+p.toJsonIndentStr:"",h=g?"\n":"",b=g?" ":"";if(a instanceof Array)return"["+H.map(a,function(a,b){var c=t(a,r?void 0:k(e,b),n);"string"!=typeof c&&(c="undefined");return h+n+c}).join(","+b)+h+f+"]";var q=[];r&&"undefined"===typeof a[B]&&q.push(h+n+p._escapeString(B)+":"+b+p.toJson(a.__id));for(var c in a)if(a.hasOwnProperty(c)){var u;if("number"==typeof c)u='"'+c+'"';else if("string"==typeof c&&("_"!=c.charAt(0)||"_"!=c.charAt(1)))u=p._escapeString(c);
else continue;var d=t(a[c],r?void 0:k(e,c),n);"string"==typeof d&&q.push(h+n+u+":"+b+d)}return"{"+q.join(","+b)+h+f+"}"}return"function"==typeof a&&v.json.ref.serializeFunctions?a.toString():p.toJson(a)}var A=this._useRefs,k=this._addProp,x=this.refAttribute;m=m||"";var l={},s={},r=B?!0:!1,C=1;e=t(e,r?void 0:"#","");if(!q)for(var w in s)delete s[w].__id;return e},_addProp:function(e,g){return e+(e.match(/#/)?1==e.length?"":".":"#")+g},refAttribute:"$ref",_useRefs:!1,serializeFunctions:!1}});
/// ref.js.map