//>>built
define("dojo/on",["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(v,w,f){function x(a,b,c,d,e){if(d=b.match(/(.*):(.*)/))return b=d[2],d=d[1],g.selector(d,b).call(e,a,c);y.test(b)&&(c=m(c));!f("event-orientationchange")&&"orientationchange"==b&&(b="resize",a=window,c=m(c));n&&(c=n(c));if(a.addEventListener){var k=b in p,l=k?p[b]:b;a.addEventListener(l,c,k);return{remove:function(){a.removeEventListener(l,c,k)}}}if(q&&a.attachEvent)return q(a,"on"+b,c);throw Error("Target must be an event emitter");
}function z(){this.cancelable=!1;this.defaultPrevented=!0}function A(){this.bubbles=!1}var r=window.ScriptEngineMajorVersion;f.add("jscript",r&&r()+ScriptEngineMinorVersion()/10);f.add("event-orientationchange",!f("android"));f.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);f.add("event-focusin",function(a,b,c){return"onfocusin"in c});f.add("touch-can-modify-event-delegate",function(){var a=function(){};a.prototype=document.createEvent("MouseEvents");
try{var b=new a;b.target=null;return null===b.target}catch(c){return!1}});var g=function(a,b,c,d){return"function"==typeof a.on&&"function"!=typeof b&&!a.nodeType?a.on(b,c):g.parse(a,b,c,x,d,this)};g.pausable=function(a,b,c,d){var e;a=g(a,b,function(){if(!e)return c.apply(this,arguments)},d);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};g.once=function(a,b,c,d){var e=g(a,b,function(){e.remove();return c.apply(this,arguments)});return e};g.parse=function(a,b,c,d,e,k){if(b.call)return b.call(k,
a,c);if(b instanceof Array)l=b;else if(-1<b.indexOf(","))var l=b.split(/\s*,\s*/);if(l){var f=[];b=0;for(var h;h=l[b++];)f.push(g.parse(a,h,c,d,e,k));f.remove=function(){for(var a=0;a<f.length;a++)f[a].remove()};return f}return d(a,b,c,e,k)};var y=/^touch/;g.matches=function(a,b,c,d,e){e=e&&e.matches?e:w.query;d=!1!==d;1!=a.nodeType&&(a=a.parentNode);for(;!e.matches(a,b,c);)if(a==c||!1===d||!(a=a.parentNode)||1!=a.nodeType)return!1;return a};g.selector=function(a,b,c){return function(d,e){function k(b){return g.matches(b,
a,d,c,f)}var f="function"==typeof a?{matches:a}:this,h=b.bubble;return h?g(d,h(k),e):g(d,b,function(a){var b=k(a.target);if(b)return e.call(b,a)})}};var B=[].slice,C=g.emit=function(a,b,c){var d=B.call(arguments,2),e="on"+b;if("parentNode"in a){var f=d[0]={},g;for(g in c)f[g]=c[g];f.preventDefault=z;f.stopPropagation=A;f.target=a;f.type=b;c=f}do a[e]&&a[e].apply(a,d);while(c&&c.bubbles&&(a=a.parentNode));return c&&c.cancelable&&c},p=f("event-focusin")?{}:{focusin:"focus",focusout:"blur"};if(!f("event-stopimmediatepropagation"))var D=
function(){this.modified=this.immediatelyStopped=!0},n=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=D,a.apply(this,arguments)}};if(f("dom-addeventlistener"))g.emit=function(a,b,c){if(a.dispatchEvent&&document.createEvent){var d=(a.ownerDocument||document).createEvent("HTMLEvents");d.initEvent(b,!!c.bubbles,!!c.cancelable);for(var e in c)e in d||(d[e]=c[e]);return a.dispatchEvent(d)&&d}return C.apply(g,arguments)};else{g._fixEvent=function(a,b){a||(a=(b&&
(b.ownerDocument||b.document||b).parentWindow||window).event);if(!a)return a;try{h&&(a.type==h.type&&a.srcElement==h.target)&&(a=h)}catch(c){}if(!a.target)switch(a.target=a.srcElement,a.currentTarget=b||a.srcElement,"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=a.toElement),a.stopPropagation||(a.stopPropagation=E,a.preventDefault=F),a.type){case "keypress":var d="charCode"in a?a.charCode:a.keyCode;10==d?(d=0,a.keyCode=13):13==d||27==d?d=0:3==d&&(d=99);a.charCode=
d;d=a;d.keyChar=d.charCode?String.fromCharCode(d.charCode):"";d.charOrCode=d.keyChar||d.keyCode}return a};var h,s=function(a){this.handle=a};s.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var G=function(a){return function(b){b=g._fixEvent(b,this);var c=a.call(this,b);b.modified&&(h||setTimeout(function(){h=null}),h=b);return c}},q=function(a,b,c){c=G(c);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>f("jscript"))&&!f("config-_allow_leaks")){"undefined"==
typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var d=a[b];if(!d||!d.listeners){var e=d,d=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");d.listeners=[];a[b]=d;d.global=this;e&&d.listeners.push(_dojoIEListeners_.push(e)-1)}d.listeners.push(a=d.global._dojoIEListeners_.push(c)-1);return new s(a)}return v.after(a,b,c,!0)},E=function(){this.cancelBubble=
!0},F=g._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}var t=function(){},u=window.orientation,m=function(a){return function(b){var c=b.corrected;if(!c){var d=b.type;try{delete b.type}catch(e){}if(b.type){if(f("touch-can-modify-event-delegate"))t.prototype=b,c=new t;else{var c={},g;for(g in b)c[g]=b[g]}c.preventDefault=function(){b.preventDefault()};c.stopPropagation=function(){b.stopPropagation()}}else c=
b,c.type=d;b.corrected=c;if("resize"==d){if(u==window.orientation)return null;u=window.orientation;c.type="orientationchange";return a.call(this,c)}"rotation"in c||(c.rotation=0,c.scale=1);var d=c.changedTouches[0],h;for(h in d)delete c[h],c[h]=d[h]}return a.call(this,c)}};return g});
/// on.js.map