//>>built
define("dojo/selector/acme",["../dom","../sniff","../_base/array","../_base/lang","../_base/window"],function(N,n,E,F,x){var O=F.trim,K=E.forEach,P="BackCompat"==x.doc.compatMode,t=!1,y=function(){return!0},L=function(b){b=0<="\x3e~+".indexOf(b.slice(-1))?b+" * ":b+" ";for(var a=function(a,c){return O(b.slice(a,c))},c=[],d=-1,f=-1,e=-1,g=-1,m=-1,r=-1,z=-1,G,A="",l="",n,k=0,s=b.length,h=null,p=null,q=function(){0<=r&&(h.id=a(r,k).replace(/\\/g,""),r=-1);if(0<=z){var b=z==k?null:a(z,k);h[0>"\x3e~+".indexOf(b)?
"tag":"oper"]=b;z=-1}0<=m&&(h.classes.push(a(m+1,k).replace(/\\/g,"")),m=-1)};A=l,l=b.charAt(k),k<s;k++)if("\\"!=A)if(h||(n=k,h={query:null,pseudos:[],attrs:[],classes:[],tag:null,oper:null,id:null,getTag:function(){return t?this.otag:this.tag}},z=k),G)l==G&&(G=null);else if("'"==l||'"'==l)G=l;else if(0<=d)if("]"==l){p.attr?p.matchFor=a(e||d+1,k):p.attr=a(d+1,k);if((d=p.matchFor)&&('"'==d.charAt(0)||"'"==d.charAt(0)))p.matchFor=d.slice(1,-1);p.matchFor&&(p.matchFor=p.matchFor.replace(/\\/g,""));h.attrs.push(p);
p=null;d=e=-1}else"\x3d"==l&&(e=0<="|~^$*".indexOf(A)?A:"",p.type=e+l,p.attr=a(d+1,k-e.length),e=k+1);else 0<=f?")"==l&&(0<=g&&(p.value=a(f+1,k)),g=f=-1):"#"==l?(q(),r=k+1):"."==l?(q(),m=k):":"==l?(q(),g=k):"["==l?(q(),d=k,p={}):"("==l?(0<=g&&(p={name:a(g+1,k),value:null},h.pseudos.push(p)),f=k):" "==l&&A!=l&&(q(),0<=g&&h.pseudos.push({name:a(g+1,k)}),h.loops=h.pseudos.length||h.attrs.length||h.classes.length,h.oquery=h.query=a(n,k),h.otag=h.tag=h.oper?null:h.tag||"*",h.tag&&(h.tag=h.tag.toUpperCase()),
c.length&&c[c.length-1].oper&&(h.infixOper=c.pop(),h.query=h.infixOper.query+" "+h.query),c.push(h),h=null);return c},u=function(b,a){return!b?a:!a?b:function(){return b.apply(window,arguments)&&a.apply(window,arguments)}},B=function(b,a){var c=a||[];b&&c.push(b);return c},H=function(b){return 1==b.nodeType},v=function(b,a){return!b?"":"class"==a?b.className||"":"for"==a?b.htmlFor||"":"style"==a?b.style.cssText||"":(t?b.getAttribute(a):b.getAttribute(a,2))||""},Q={"*\x3d":function(b,a){return function(c){return 0<=
v(c,b).indexOf(a)}},"^\x3d":function(b,a){return function(c){return 0==v(c,b).indexOf(a)}},"$\x3d":function(b,a){return function(c){c=" "+v(c,b);var d=c.lastIndexOf(a);return-1<d&&d==c.length-a.length}},"~\x3d":function(b,a){var c=" "+a+" ";return function(a){return 0<=(" "+v(a,b)+" ").indexOf(c)}},"|\x3d":function(b,a){var c=a+"-";return function(d){d=v(d,b);return d==a||0==d.indexOf(c)}},"\x3d":function(b,a){return function(c){return v(c,b)==a}}};F=x.doc.documentElement;var I=!(F.nextElementSibling||
"nextElementSibling"in F),C=!I?"nextElementSibling":"nextSibling",ca=!I?"previousElementSibling":"previousSibling",D=I?H:y,R=function(b){for(;b=b[ca];)if(D(b))return!1;return!0},S=function(b){for(;b=b[C];)if(D(b))return!1;return!0},J=function(b){var a=b.parentNode,a=7!=a.nodeType?a:a.nextSibling,c=0,d=a.children||a.childNodes,f=b._i||b.getAttribute("_i")||-1,e=a._l||("undefined"!==typeof a.getAttribute?a.getAttribute("_l"):-1);if(!d)return-1;d=d.length;if(e==d&&0<=f&&0<=e)return f;n("ie")&&"undefined"!==
typeof a.setAttribute?a.setAttribute("_l",d):a._l=d;f=-1;for(a=a.firstElementChild||a.firstChild;a;a=a[C])D(a)&&(n("ie")?a.setAttribute("_i",++c):a._i=++c,b===a&&(f=c));return f},da=function(b){return!(J(b)%2)},ea=function(b){return J(b)%2},T={checked:function(b,a){return function(a){return!!("checked"in a?a.checked:a.selected)}},disabled:function(b,a){return function(a){return a.disabled}},enabled:function(b,a){return function(a){return!a.disabled}},"first-child":function(){return R},"last-child":function(){return S},
"only-child":function(b,a){return function(a){return R(a)&&S(a)}},empty:function(b,a){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var f=b[a].nodeType;if(1===f||3==f)return!1}return!0}},contains:function(b,a){var c=a.charAt(0);if('"'==c||"'"==c)a=a.slice(1,-1);return function(b){return 0<=b.innerHTML.indexOf(a)}},not:function(b,a){var c=L(a)[0],d={el:1};"*"!=c.tag&&(d.tag=1);c.classes.length||(d.classes=1);var f=s(c,d);return function(a){return!f(a)}},"nth-child":function(b,
a){var c=parseInt;if("odd"==a)return ea;if("even"==a)return da;if(-1!=a.indexOf("n")){var d=a.split("n",2),f=d[0]?"-"==d[0]?-1:c(d[0]):1,e=d[1]?c(d[1]):0,g=0,m=-1;0<f?0>e?e=e%f&&f+e%f:0<e&&(e>=f&&(g=e-e%f),e%=f):0>f&&(f*=-1,0<e&&(m=e,e%=f));if(0<f)return function(a){a=J(a);return a>=g&&(0>m||a<=m)&&a%f==e};a=e}var r=c(a);return function(a){return J(a)==r}}},fa=9>n("ie")||9==n("ie")&&n("quirks")?function(b){var a=b.toLowerCase();"class"==a&&(b="className");return function(c){return t?c.getAttribute(b):
c[b]||c[a]}}:function(b){return function(a){return a&&a.getAttribute&&a.hasAttribute(b)}},s=function(b,a){if(!b)return y;a=a||{};var c=null;"el"in a||(c=u(c,H));"tag"in a||"*"!=b.tag&&(c=u(c,function(a){return a&&(t?a.tagName:a.tagName.toUpperCase())==b.getTag()}));"classes"in a||K(b.classes,function(a,b,e){var g=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=u(c,function(a){return g.test(a.className)});c.count=b});"pseudos"in a||K(b.pseudos,function(a){var b=a.name;T[b]&&(c=u(c,T[b](b,a.value)))});"attrs"in
a||K(b.attrs,function(a){var b,e=a.attr;a.type&&Q[a.type]?b=Q[a.type](e,a.matchFor):e.length&&(b=fa(e));b&&(c=u(c,b))});"id"in a||b.id&&(c=u(c,function(a){return!!a&&a.id==b.id}));c||"default"in a||(c=y);return c},ga=function(b){return function(a,c,d){for(;a=a[C];)if(!I||H(a)){(!d||w(a,d))&&b(a)&&c.push(a);break}return c}},ha=function(b){return function(a,c,d){for(a=a[C];a;){if(D(a)){if(d&&!w(a,d))break;b(a)&&c.push(a)}a=a[C]}return c}},U=function(b,a){var c=function(a){var b=[];try{b=Array.prototype.slice.call(a)}catch(c){for(var g=
0,m=a.length;g<m;g++)b.push(a[g])}return b};b=b||y;return function(d,f,e){var g=0,m=[],m=c(d.children||d.childNodes);for(a&&E.forEach(m,function(a){1===a.nodeType&&(m=m.concat(c(a.getElementsByTagName("*"))))});d=m[g++];)D(d)&&((!e||w(d,e))&&b(d,g))&&f.push(d);return f}},V=function(b,a){for(var c=b.parentNode;c&&c!=a;)c=c.parentNode;return!!c},W={},X=function(b){var a=W[b.query];if(a)return a;var c=b.infixOper,c=c?c.oper:"",d=s(b,{el:1}),f="*"==b.tag,e=x.doc.getElementsByClassName;if(c)e={el:1},f&&
(e.tag=1),d=s(b,e),"+"==c?a=ga(d):"~"==c?a=ha(d):"\x3e"==c&&(a=U(d));else if(b.id)d=!b.loops&&f?y:s(b,{el:1,id:1}),a=function(a,c){var e=N.byId(b.id,a.ownerDocument||a);a.ownerDocument&&!V(a,a.ownerDocument)&&E.some(11===a.nodeType?a.childNodes:[a],function(a){a=U(function(a){return a.id===b.id},!0)(a,[]);if(a.length)return e=a[0],!1});if(e&&d(e)&&(9==a.nodeType||V(e,a)))return B(e,c)};else if(e&&/\{\s*\[native code\]\s*\}/.test(String(e))&&b.classes.length&&!P)var d=s(b,{el:1,classes:1,id:1}),g=
b.classes.join(" "),a=function(a,b,c){b=B(0,b);for(var e,f=0,l=a.getElementsByClassName(g);e=l[f++];)d(e,a)&&w(e,c)&&b.push(e);return b};else!f&&!b.loops?a=function(a,c,d){c=B(0,c);for(var e=0,f=b.getTag(),f=f?a.getElementsByTagName(f):[];a=f[e++];)w(a,d)&&c.push(a);return c}:(d=s(b,{el:1,tag:1,id:1}),a=function(a,c,e){c=B(0,c);for(var f,g=0,l=(f=b.getTag())?a.getElementsByTagName(f):[];f=l[g++];)d(f,a)&&w(f,e)&&c.push(f);return c});return W[b.query]=a},Y={},Z={},$=function(b){var a=L(O(b));if(1==
a.length){var c=X(a[0]);return function(a){if(a=c(a,[]))a.nozip=!0;return a}}return function(b){b=B(b);for(var c,e,g=a.length,m,r,n=0;n<g;n++){r=[];c=a[n];e=b.length-1;0<e&&(m={},r.nozip=!0);e=X(c);for(var q=0;c=b[q];q++)e(c,r,m);if(!r.length)break;b=r}return r}},ia=n("ie")?"commentStrip":"nozip",aa=!!x.doc.querySelectorAll,ja=/\\[>~+]|n\+\d|([^ \\])?([>~+])([^ =])?/g,ka=function(b,a,c,d){return c?(a?a+" ":"")+c+(d?" "+d:""):b},la=/([^[]*)([^\]]*])?/g,ma=function(b,a,c){return a.replace(ja,ka)+(c||
"")},ba=function(b,a){b=b.replace(la,ma);if(aa){var c=Z[b];if(c&&!a)return c}if(c=Y[b])return c;var c=b.charAt(0),d=-1==b.indexOf(" ");0<=b.indexOf("#")&&d&&(a=!0);if(aa&&!a&&-1=="\x3e~+".indexOf(c)&&(!n("ie")||-1==b.indexOf(":"))&&!(P&&0<=b.indexOf("."))&&-1==b.indexOf(":contains")&&-1==b.indexOf(":checked")&&-1==b.indexOf("|\x3d")){var f=0<="\x3e~+".indexOf(b.charAt(b.length-1))?b+" *":b;return Z[b]=function(a){if(9==a.nodeType||d)try{var c=a.querySelectorAll(f);c[ia]=!0;return c}catch(e){}return ba(b,
!0)(a)}}var e=b.match(/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g);return Y[b]=2>e.length?$(b):function(a){for(var b=0,c=[],d;d=e[b++];)c=c.concat($(d)(a));return c}},q=0,na=n("ie")?function(b){return t?b.getAttribute("_uid")||b.setAttribute("_uid",++q)||q:b.uniqueID}:function(b){return b._uid||(b._uid=++q)},w=function(b,a){if(!a)return 1;var c=na(b);return!a[c]?a[c]=1:0},oa=function(b){if(b&&b.nozip)return b;if(!b||!b.length)return[];if(2>b.length)return[b[0]];var a=[];q++;var c,d;if(n("ie")&&
t){var f=q+"";for(c=0;c<b.length;c++)if((d=b[c])&&d.getAttribute("_zipIdx")!=f)a.push(d),d.setAttribute("_zipIdx",f)}else if(n("ie")&&b.commentStrip)try{for(c=0;c<b.length;c++)(d=b[c])&&H(d)&&a.push(d)}catch(e){}else for(c=0;c<b.length;c++)if((d=b[c])&&d._zipIdx!=q)a.push(d),d._zipIdx=q;return a},M=function(b,a){a=a||x.doc;t="div"===(a.ownerDocument||a).createElement("div").tagName;var c=ba(b)(a);return c&&c.nozip?c:oa(c)};M.filter=function(b,a,c){for(var d=[],f=L(a),f=1==f.length&&!/[^\w#\.]/.test(a)?
s(f[0]):function(b){return-1!=E.indexOf(M(a,N.byId(c)),b)},e=0,g;g=b[e];e++)f(g)&&d.push(g);return d};return M});
/// acme.js.map