//>>built
define("dojox/charting/plot2d/CartesianBase","dojo/_base/lang dojo/_base/declare dojo/_base/connect dojo/has ./Base ../scaler/primitive dojox/gfx dojox/gfx/fx dojox/lang/utils".split(" "),function(p,q,r,w,s,m,t,u,v){var n=function(){return!1};return q("dojox.charting.plot2d.CartesianBase",s,{baseParams:{hAxis:"x",vAxis:"y",labels:!1,labelOffset:10,fixed:!0,precision:1,labelStyle:"inside",htmlLabels:!0,omitLabels:!0,labelFunc:null},constructor:function(b,a){this.axes=["hAxis","vAxis"];this.zoom=null;
this.zoomQueue=[];this.lastWindow={vscale:1,hscale:1,xoffset:0,yoffset:0};this.hAxis=a&&a.hAxis||"x";this.vAxis=a&&a.vAxis||"y";this.series=[];this.opt=p.clone(this.baseParams);v.updateWithObject(this.opt,a)},clear:function(){this.inherited(arguments);this._vAxis=this._hAxis=null;return this},cleanGroup:function(b,a){this.inherited(arguments);if(!a&&this.chart._nativeClip){var d=this.chart.offsets,c=this.chart.dim,e=Math.max(0,c.width-d.l-d.r),c=Math.max(0,c.height-d.t-d.b);this.group.setClip({x:d.l,
y:d.t,width:e,height:c});this._clippedGroup||(this._clippedGroup=this.group.createGroup())}},purgeGroup:function(){this.inherited(arguments);this._clippedGroup=null},getGroup:function(){return this._clippedGroup||this.group},setAxis:function(b){b&&(this[b.vertical?"_vAxis":"_hAxis"]=b);return this},toPage:function(b){var a=this._hAxis,d=this._vAxis,c=a.getScaler(),e=d.getScaler(),g=c.scaler.getTransformerFromModel(c),f=e.scaler.getTransformerFromModel(e),h=this.chart.getCoords(),k=this.chart.offsets,
l=this.chart.dim,c=function(b){var c={};c.x=g(b[a.name])+h.x+k.l;c.y=h.y+l.height-k.b-f(b[d.name]);return c};return b?c(b):c},toData:function(b){var a=this._hAxis,d=this._vAxis,c=a.getScaler(),e=d.getScaler(),g=c.scaler.getTransformerFromPlot(c),f=e.scaler.getTransformerFromPlot(e),h=this.chart.getCoords(),k=this.chart.offsets,l=this.chart.dim,c=function(b){var c={};c[a.name]=g(b.x-h.x-k.l);c[d.name]=f(h.y+l.height-b.y-k.b);return c};return b?c(b):c},isDirty:function(){return this.dirty||this._hAxis&&
this._hAxis.dirty||this._vAxis&&this._vAxis.dirty},createLabel:function(b,a,d,c){if(this.opt.labels){var e,g=this.opt.labelFunc?this.opt.labelFunc.apply(this,[a,this.opt.fixed,this.opt.precision]):this._getLabel(isNaN(a.y)?a:a.y);if("inside"==this.opt.labelStyle){var f=t._base._getTextBox(g,{font:c.series.font});a=d.x+d.width/2;e=d.y+d.height/2+f.h/4;if(f.w>d.width||f.h>d.height)return}else a=d.x+d.width/2,e=d.y-this.opt.labelOffset;this.renderLabel(b,a,e,g,c,"inside"==this.opt.labelStyle)}},performZoom:function(b,
a){var d=this._vAxis.scale||1,c=this._hAxis.scale||1,e=b.height-a.b,g=this._hScaler.bounds,g=(g.from-g.lower)*g.scale,f=this._vScaler.bounds,f=(f.from-f.lower)*f.scale,h=d/this.lastWindow.vscale,k=c/this.lastWindow.hscale,l=(this.lastWindow.xoffset-g)/(1==this.lastWindow.hscale?c:this.lastWindow.hscale),m=(f-this.lastWindow.yoffset)/(1==this.lastWindow.vscale?d:this.lastWindow.vscale),n=this.getGroup(),e=u.animateTransform(p.delegate({shape:n,duration:1200,transform:[{name:"translate",start:[0,0],
end:[a.l*(1-k),e*(1-h)]},{name:"scale",start:[1,1],end:[k,h]},{name:"original"},{name:"translate",start:[0,0],end:[l,m]}]},this.zoom));p.mixin(this.lastWindow,{vscale:d,hscale:c,xoffset:g,yoffset:f});this.zoomQueue.push(e);r.connect(e,"onEnd",this,function(){this.zoom=null;this.zoomQueue.shift();0<this.zoomQueue.length&&this.zoomQueue[0].play()});1==this.zoomQueue.length&&this.zoomQueue[0].play();return this},initializeScalers:function(b,a){this._hAxis?(this._hAxis.initialized()||this._hAxis.calculate(a.hmin,
a.hmax,b.width),this._hScaler=this._hAxis.getScaler()):this._hScaler=m.buildScaler(a.hmin,a.hmax,b.width);this._vAxis?(this._vAxis.initialized()||this._vAxis.calculate(a.vmin,a.vmax,b.height),this._vScaler=this._vAxis.getScaler()):this._vScaler=m.buildScaler(a.vmin,a.vmax,b.height);return this},isNullValue:function(b){if(null===b||"undefined"==typeof b)return!0;var a=this._hAxis?this._hAxis.isNullValue:n,d=this._vAxis?this._vAxis.isNullValue:n;return"number"==typeof b?a(1)||d(b):a(isNaN(b.x)?1:b.x)||
null===b.y||d(b.y)}})});
/// CartesianBase.js.map