//>>built
define("dojox/charting/plot2d/Columns","dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/has ./CartesianBase ./_PlotEvents ./common dojox/lang/functional dojox/lang/functional/reversed dojox/lang/utils dojox/gfx/fx".split(" "),function(q,z,F,N,G,H,t,I,J,A,K){var L=J.lambda("item.purgeGroup()"),u=function(){return!1};return F("dojox.charting.plot2d.Columns",[G,H],{defaultParams:{gap:0,animate:null,enableCache:!1},optionalParams:{minBarSize:1,maxBarSize:1,stroke:{},outline:{},shadow:{},fill:{},
filter:{},styleFunc:null,font:"",fontColor:""},constructor:function(a,d){this.opt=q.clone(q.mixin(this.opt,this.defaultParams));A.updateWithObject(this.opt,d);A.updateWithPattern(this.opt,d,this.optionalParams);this.animate=this.opt.animate;this.renderingOptions={"shape-rendering":"crispEdges"}},getSeriesStats:function(){var a=t.collectSimpleStats(this.series,q.hitch(this,"isNullValue"));a.hmin-=0.5;a.hmax+=0.5;return a},createRect:function(a,d,b){var e;this.opt.enableCache&&0<a._rectFreePool.length?
(e=a._rectFreePool.pop(),e.setShape(b),d.add(e)):e=d.createRect(b);this.opt.enableCache&&a._rectUsePool.push(e);return e},render:function(a,d){if(this.zoom&&!this.isDataDirty())return this.performZoom(a,d);this.resetEvents();this.dirty=this.isDirty();var b;this.dirty&&(z.forEach(this.series,L),this._eventSeries={},this.cleanGroup(),b=this.getGroup(),I.forEachRev(this.series,function(a){a.cleanGroup(b)}));var e=this.chart.theme,n=this._hScaler.scaler.getTransformerFromModel(this._hScaler),f=this._vScaler.scaler.getTransformerFromModel(this._vScaler),
k=Math.max(this._vScaler.bounds.lower,this._vAxis?this._vAxis.naturalBaseline:0),l=f(k),M=this.events(),B=this.getBarProperties(),C=this.series.length;z.forEach(this.series,function(a){a.hidden&&C--});for(var D=this.extractValues(this._hScaler),D=this.rearrangeValues(D,f,l),v=0;v<this.series.length;v++){var c=this.series[v];if(!this.dirty&&!c.dirty)e.skip(),this._reconnectEvents(c.name);else{c.cleanGroup();this.opt.enableCache&&(c._rectFreePool=(c._rectFreePool?c._rectFreePool:[]).concat(c._rectUsePool?
c._rectUsePool:[]),c._rectUsePool=[]);var E=e.next("column",[this.opt,c]),t=Array(c.data.length);if(c.hidden)c.dyn.fill=E.series.fill;else{C--;b=c.group;for(var w=z.some(c.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),h=w?Math.max(0,Math.floor(this._hScaler.bounds.from-1)):0,A=w?Math.min(c.data.length,Math.ceil(this._hScaler.bounds.to)):c.data.length;h<A;++h){var s=c.data[h];if(!this.isNullValue(s)){var r=this.getValue(s,h,v,w);f(r.y);var x=D[v][h],g,p;this.opt.styleFunc||
"number"!=typeof s?(g="number"!=typeof s?[s]:[],this.opt.styleFunc&&g.push(this.opt.styleFunc(s)),g=e.addMixin(E,"column",g,!0)):g=e.post(E,"column");if(1<=B.width){var y={x:d.l+n(r.x+0.5)+B.gap+B.thickness*C,y:a.height-d.b-l-Math.max(x,0),width:B.width,height:Math.abs(x)};g.series.shadow&&(p=q.clone(y),p.x+=g.series.shadow.dx,p.y+=g.series.shadow.dy,p=this.createRect(c,b,p).setFill(g.series.shadow.color).setStroke(g.series.shadow),this.animate&&this._animateColumn(p,a.height-d.b+l,x));var m=this._plotFill(g.series.fill,
a,d),m=this._shapeFill(m,y),m=this.createRect(c,b,y).setFill(m).setStroke(g.series.stroke);this.overrideShape(m,{index:h,value:r});m.setFilter&&g.series.filter&&m.setFilter(g.series.filter);c.dyn.fill=m.getFill();c.dyn.stroke=m.getStroke();if(M){var u={element:"column",index:h,run:c,shape:m,shadow:p,cx:r.x+0.5,cy:r.y,x:w?h:c.data[h].x,y:w?c.data[h]:c.data[h].y};this._connectEvents(u);t[h]=u}!isNaN(r.py)&&r.py>k&&(y.height=x-f(r.py));this.createLabel(b,s,y,g);this.animate&&this._animateColumn(m,a.height-
d.b-l,x)}}}this._eventSeries[c.name]=t;c.dirty=!1}}}this.dirty=!1;return this},getValue:function(a,d,b,e){e?(b="number"==typeof a?a:a.y,a=d):(b=a.y,a=a.x-1);return{x:a,y:b}},extractValues:function(a){for(var d=[],b=this.series.length-1;0<=b;--b){var e=this.series[b];if(this.dirty||e.dirty){var n=z.some(e.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),f=n?Math.max(0,Math.floor(a.bounds.from-1)):0,n=n?Math.min(e.data.length,Math.ceil(a.bounds.to)):e.data.length,k=d[b]=[];k.min=
f;for(k.max=n;f<n;++f){var l=e.data[f];k[f]=this.isNullValue(l)?0:"number"==typeof l?l:l.y}}}return d},rearrangeValues:function(a,d,b){for(var e=0,n=a.length;e<n;++e){var f=a[e];if(f)for(var k=f.min,l=f.max;k<l;++k){var q=f[k];f[k]=this.isNullValue(q)?0:d(q)-b}}return a},isNullValue:function(a){if(null===a||"undefined"==typeof a)return!0;var d=this._hAxis?this._hAxis.isNullValue:u,b=this._vAxis?this._vAxis.isNullValue:u;return"number"==typeof a?b(0.5)||d(a):b(isNaN(a.x)?0.5:a.x+0.5)||null===a.y||
d(a.y)},getBarProperties:function(){var a=t.calculateBarSize(this._hScaler.bounds.scale,this.opt);return{gap:a.gap,width:a.size,thickness:0}},_animateColumn:function(a,d,b){0===b&&(b=1);K.animateTransform(q.delegate({shape:a,duration:1200,transform:[{name:"translate",start:[0,d-d/b],end:[0,0]},{name:"scale",start:[1,1/b],end:[1,1]},{name:"original"}]},this.animate)).play()}})});
/// Columns.js.map