//>>built
define("dojox/charting/plot2d/Spider","dojo/_base/lang dojo/_base/declare dojo/_base/connect dojo/_base/array dojo/dom-geometry dojo/_base/fx dojo/fx dojo/sniff ./Base ./_PlotEvents ./common ../axis2d/common dojox/gfx dojox/gfx/matrix dojox/gfx/fx dojox/lang/functional dojox/lang/utils dojo/fx/easing".split(" "),function(B,T,I,J,P,K,U,V,W,X,L,Q,C,Y,aa,R,S,Z){return T("dojox.charting.plot2d.Spider",[W,X],{defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:-10,labelStyle:"default",htmlLabels:!0,
startAngle:-90,divisions:3,axisColor:"",axisWidth:0,spiderColor:"",spiderWidth:0,seriesWidth:0,seriesFillAlpha:0.2,spiderOrigin:0.16,markerSize:3,spiderType:"polygon",animationType:Z.backOut,animate:null,axisTickFont:"",axisTickFontColor:"",axisFont:"",axisFontColor:""},optionalParams:{radius:0,font:"",fontColor:""},constructor:function(a,e){this.opt=B.clone(this.defaultParams);S.updateWithObject(this.opt,e);S.updateWithPattern(this.opt,e,this.optionalParams);this.dyn=[];this.datas={};this.labelKey=
[];this.oldSeriePoints={};this.animate=null===this.opt.animate?{}:this.opt.animate;this.animations={}},clear:function(){this.inherited(arguments);this.dyn=[];this.axes=[];this.datas={};this.labelKey=[];this.oldSeriePoints={};this.animations={};return this},setAxis:function(a){a&&(void 0!=a.opt.min&&(this.datas[a.name].min=a.opt.min),void 0!=a.opt.max&&(this.datas[a.name].max=a.opt.max));return this},addSeries:function(a){this.series.push(a);for(var e in a.data){var b=a.data[e],k=this.datas[e];k?(k.vlist.push(b),
k.min=Math.min(k.min,b),k.max=Math.max(k.max,b)):(k="__"+e,this.axes.push(k),this[k]=e,this.datas[e]={min:b,max:b,vlist:[b]})}if(0>=this.labelKey.length)for(e in a.data)this.labelKey.push(e);return this},getSeriesStats:function(){return L.collectSimpleStats(this.series,function(a){return null===a})},render:function(a,e){if(!this.dirty)return this;this.dirty=!1;this.cleanGroup();var b=this.group,k=this.chart.theme;this.resetEvents();if(!this.series||!this.series.length)return this;var c=this.opt,f=
k.axis,d=(a.width-e.l-e.r)/2,h=(a.height-e.t-e.b)/2,l=Math.min(d,h),r=c.font||f.majorTick&&f.majorTick.font||f.tick&&f.tick.font||"normal normal normal 7pt Tahoma",p=c.axisFont||f.tick&&f.tick.titleFont||"normal normal normal 11pt Tahoma",v=c.axisTickFontColor||f.majorTick&&f.majorTick.fontColor||f.tick&&f.tick.fontColor||"silver",N=c.axisFontColor||f.tick&&f.tick.titleFontColor||"black",x=c.axisColor||f.tick&&f.tick.axisColor||"silver",m=c.spiderColor||f.tick&&f.tick.spiderColor||"silver",$=c.axisWidth||
f.stroke&&f.stroke.width||2,y=c.spiderWidth||f.stroke&&f.stroke.width||2,f=c.seriesWidth||f.stroke&&f.stroke.width||2,s=C.normalizedLength(C.splitFontString(p).size),E=Y._degToRad(c.startAngle),B,t,M,u,q,z,w=c.spiderOrigin,D=3<=c.divisions?c.divisions:3,I=c.markerSize,K=c.spiderType,L=c.animationType,g=-10>c.labelOffset?c.labelOffset:-10,n;c.labels&&(l=J.map(this.series,function(a){return a.name},this),l=R.foldl1(R.map(l,function(a){return C._base._getTextBox(a,{font:k.series.font}).w},this),"Math.max(a, b)")/
2,l=Math.min(d-2*l,h-s)+g,B=l-g);"radius"in c&&(l=c.radius,B=l-g);l/=1.2;d={cx:e.l+d,cy:e.t+h,r:l};for(h=0;h<this.series.length;h++)if(n=this.series[h],!this.dirty&&!n.dirty)k.skip();else if(n.cleanGroup(),g=n.data,null!==g&&(s=this._getObjectLength(g),!t||0>=t.length))if(t=[],M=[],z=[],this._buildPoints(t,s,d,l,E,!0,a),this._buildPoints(M,s,d,l*w,E,!0,a),this._buildPoints(z,s,d,B,E,!1,a),2<D){u=[];q=[];for(g=0;g<D-2;g++)u[g]=[],this._buildPoints(u[g],s,d,l*(w+(1-w)*(g+1)/(D-1)),E,!0,a),q[g]=l*(w+
(1-w)*(g+1)/(D-1))}s=b.createGroup();x={color:x,width:$};h={color:m,width:y};for(g=t.length-1;0<=g;--g)m=t[g],y={x:m.x+0.2*(m.x-d.cx),y:m.y+0.2*(m.y-d.cy)},m={x:m.x+0.2*(m.x-d.cx)/2,y:m.y+0.2*(m.y-d.cy)/2},s.createLine({x1:d.cx,y1:d.cy,x2:y.x,y2:y.y}).setStroke(x),this._drawArrow(s,y,m,x);s=b.createGroup();for(g=z.length-1;0<=g;--g)m=z[g],y=C._base._getTextBox(this.labelKey[g],{font:p}).w||0,x=this.opt.htmlLabels&&"vml"!=C.renderer?"html":"gfx",m=Q.createText[x](this.chart,s,!P.isBodyLtr()&&"html"==
x?m.x+y-a.width:m.x,m.y,"middle",this.labelKey[g],p,N),this.opt.htmlLabels&&this.htmlElements.push(m);p=b.createGroup();if("polygon"==K){if(p.createPolyline(t).setStroke(h),p.createPolyline(M).setStroke(h),0<u.length)for(g=u.length-1;0<=g;--g)p.createPolyline(u[g]).setStroke(h)}else if(p.createCircle({cx:d.cx,cy:d.cy,r:l}).setStroke(h),p.createCircle({cx:d.cx,cy:d.cy,r:l*w}).setStroke(h),0<q.length)for(g=q.length-1;0<=g;--g)p.createCircle({cx:d.cx,cy:d.cy,r:q[g]}).setStroke(h);s=this._getObjectLength(this.datas);
N=b.createGroup();u=0;for(var F in this.datas){q=this.datas[F];t=q.min;q=q.max;q-=t;p=E+2*Math.PI*u/s;for(h=0;h<D;h++)z=t+q*h/(D-1),m=this._getCoordinate(d,l*(w+(1-w)*h/(D-1)),p,a),z=this._getLabel(z),y=C._base._getTextBox(z,{font:r}).w||0,x=this.opt.htmlLabels&&"vml"!=C.renderer?"html":"gfx",this.opt.htmlLabels&&this.htmlElements.push(Q.createText[x](this.chart,N,!P.isBodyLtr()&&"html"==x?m.x+y-a.width:m.x,m.y,"start",z,r,v));u++}this.chart.seriesShapes={};for(h=this.series.length-1;0<=h;h--)if(n=
this.series[h],g=n.data,null!==g){var r=k.next("spider",[c,n]),G=C.normalizeColor(r.series.fill),r={color:r.series.fill,width:f};G.a=c.seriesFillAlpha;n.dyn={fill:G,stroke:r};if(!n.hidden){var A=[],H=[];u=0;for(F in g)q=this.datas[F],t=q.min,q=q.max,q-=t,v=g[F],p=E+2*Math.PI*u/s,m=this._getCoordinate(d,l*(w+(1-w)*(v-t)/q),p,a),A.push(m),H.push({sname:n.name,key:F,data:v}),u++;A[A.length]=A[0];H[H.length]=H[0];var v=this._getBoundary(A),O=n.group,r=this._createSeriesEntry(O,this.oldSeriePoints[n.name]||
M,A,G,r,l,w,I,L);this.chart.seriesShapes[n.name]=r;this.oldSeriePoints[n.name]=A;this._connectEvents({element:"spider_poly",index:h,id:"spider_poly_"+n.name,run:n,plot:this,shape:r.poly,parent:O,brect:v,cx:d.cx,cy:d.cy,cr:l,f:G,s:b});this._connectEvents({element:"spider_plot",index:h,id:"spider_plot_"+n.name,run:n,plot:this,shape:n.group});J.forEach(r.circles,function(a,c){this._connectEvents({element:"spider_circle",index:c,id:"spider_circle_"+n.name+c,run:n,plot:this,shape:a,parent:O,tdata:H[c],
cx:A[c].x,cy:A[c].y,f:G,s:b})},this)}}return this},_createSeriesEntry:function(a,e,b,k,c,f,d,h,l){f=this.animate?e:b;var r=a.createPolyline(f).setFill(k).setStroke(c),p=[];for(d=0;d<f.length;d++){var v=f[d],v=a.createCircle({cx:v.x,cy:v.y,r:h}).setFill(k).setStroke(c);p.push(v)}this.animate&&(k=J.map(b,function(a,c){var b=new K.Animation(B.delegate({duration:1E3,easing:l,curve:[e[c].y,a.y]},this.animate)),d=p[c];I.connect(b,"onAnimate",function(a){var b=r.getShape();b.points[c].y=a;r.setShape(b);
b=d.getShape();b.cy=a;d.setShape(b)});return b},this),b=J.map(b,function(a,c){var b=new K.Animation(B.delegate({duration:1E3,easing:l,curve:[e[c].x,a.x]},this.animate)),d=p[c];I.connect(b,"onAnimate",function(a){var b=r.getShape();b.points[c].x=a;r.setShape(b);b=d.getShape();b.cx=a;d.setShape(b)});return b},this),U.combine(k.concat(b)).play());return{group:a,poly:r,circles:p}},plotEvent:function(a){"spider_plot"==a.element&&"onmouseover"==a.type&&!V("ie")&&a.shape.moveToFront()},tooltipFunc:function(a){return"spider_circle"==
a.element?a.tdata.sname+"\x3cbr/\x3e"+a.tdata.key+"\x3cbr/\x3e"+a.tdata.data:null},_getBoundary:function(a){for(var e=a[0].x,b=a[0].x,k=a[0].y,c=a[0].y,f=0;f<a.length;f++)var d=a[f],e=Math.max(d.x,e),k=Math.max(d.y,k),b=Math.min(d.x,b),c=Math.min(d.y,c);return{x:b,y:c,width:e-b,height:k-c}},_drawArrow:function(a,e,b,k){var c=Math.sqrt(Math.pow(b.x-e.x,2)+Math.pow(b.y-e.y,2)),f=(b.y-e.y)/c,d=(b.x-e.x)/c;a.createPolyline([e,{x:b.x+c/3*-f,y:b.y+c/3*d},{x:b.x+c/3*f,y:b.y+c/3*-d}]).setFill(k.color).setStroke(k)},
_buildPoints:function(a,e,b,k,c,f,d){for(var h=0;h<e;h++)a.push(this._getCoordinate(b,k,c+2*Math.PI*h/e,d));f&&a.push(this._getCoordinate(b,k,c+2*Math.PI,d))},_getCoordinate:function(a,e,b,k){return{x:a.cx+e*Math.cos(b),y:a.cy+e*Math.sin(b)}},_getObjectLength:function(a){var e=0;if(B.isObject(a))for(var b in a)e++;return e},_getLabel:function(a){return L.getLabel(a,this.opt.fixed,this.opt.precision)}})});
/// Spider.js.map