//>>built
require({cache:{"url:dijit/templates/Dialog.html":'\x3cdiv class\x3d"dijitDialog" role\x3d"dialog" aria-labelledby\x3d"${id}_title"\x3e\n\t\x3cdiv data-dojo-attach-point\x3d"titleBar" class\x3d"dijitDialogTitleBar"\x3e\n\t\t\x3cspan data-dojo-attach-point\x3d"titleNode" class\x3d"dijitDialogTitle" id\x3d"${id}_title"\n\t\t\t\trole\x3d"heading" level\x3d"1"\x3e\x3c/span\x3e\n\t\t\x3cspan data-dojo-attach-point\x3d"closeButtonNode" class\x3d"dijitDialogCloseIcon" data-dojo-attach-event\x3d"ondijitclick: onCancel" title\x3d"${buttonCancel}" role\x3d"button" tabindex\x3d"-1"\x3e\n\t\t\t\x3cspan data-dojo-attach-point\x3d"closeText" class\x3d"closeText" title\x3d"${buttonCancel}"\x3ex\x3c/span\x3e\n\t\t\x3c/span\x3e\n\t\x3c/div\x3e\n\t\x3cdiv data-dojo-attach-point\x3d"containerNode" class\x3d"dijitDialogPaneContent"\x3e\x3c/div\x3e\n\t${!actionBarTemplate}\n\x3c/div\x3e\n\n'}});
define("dijit/Dialog","require dojo/_base/array dojo/aspect dojo/_base/declare dojo/Deferred dojo/dom dojo/dom-class dojo/dom-geometry dojo/dom-style dojo/_base/fx dojo/i18n dojo/keys dojo/_base/lang dojo/on dojo/ready dojo/sniff dojo/window dojo/dnd/Moveable dojo/dnd/TimedMoveable ./focus ./_base/manager ./_Widget ./_TemplatedMixin ./_CssStateMixin ./form/_FormMixin ./_DialogMixin ./DialogUnderlay ./layout/ContentPane ./layout/utils dojo/text!./templates/Dialog.html ./a11yclick dojo/i18n!./nls/common".split(" "),
function(B,h,q,w,r,C,s,m,k,x,D,y,e,z,E,A,n,F,G,f,p,N,H,I,J,K,t,L,u,M){var v=new r;v.resolve(!0);p=w("dijit._DialogBase",[H,J,K,I],{templateString:M,baseClass:"dijitDialog",cssStateNodes:{closeButtonNode:"dijitDialogCloseIcon"},_setTitleAttr:{node:"titleNode",type:"innerHTML"},open:!1,duration:p.defaultDuration,refocus:!0,autofocus:!0,_firstFocusItem:null,_lastFocusItem:null,draggable:!0,_setDraggableAttr:function(a){this._set("draggable",a)},maxRatio:0.9,closable:!0,_setClosableAttr:function(a){this.closeButtonNode.style.display=
a?"":"none";this._set("closable",a)},postMixInProperties:function(){var a=D.getLocalization("dijit","common");e.mixin(this,a);this.inherited(arguments)},postCreate:function(){k.set(this.domNode,{display:"none",position:"absolute"});this.ownerDocumentBody.appendChild(this.domNode);this.inherited(arguments);q.after(this,"onExecute",e.hitch(this,"hide"),!0);q.after(this,"onCancel",e.hitch(this,"hide"),!0);this._modalconnects=[]},onLoad:function(){this.resize();this._position();this.autofocus&&g.isTop(this)&&
(this._getFocusItems(),f.focus(this._firstFocusItem));this.inherited(arguments)},focus:function(){this._getFocusItems();f.focus(this._firstFocusItem)},_endDrag:function(){var a=m.position(this.domNode),b=n.getBox(this.ownerDocument);a.y=Math.min(Math.max(a.y,0),b.h-a.h);a.x=Math.min(Math.max(a.x,0),b.w-a.w);this._relativePosition=a;this._position()},_setup:function(){var a=this.domNode;this.titleBar&&this.draggable?(this._moveable=new (6==A("ie")?G:F)(a,{handle:this.titleBar}),q.after(this._moveable,
"onMoveStop",e.hitch(this,"_endDrag"),!0)):s.add(a,"dijitDialogFixed");this.underlayAttrs={dialogId:this.id,"class":h.map(this["class"].split(/\s/),function(a){return a+"_underlay"}).join(" "),_onKeyDown:e.hitch(this,"_onKey"),ownerDocument:this.ownerDocument}},_size:function(){this.resize()},_position:function(){if(!s.contains(this.ownerDocumentBody,"dojoMove")){var a=this.domNode,b=n.getBox(this.ownerDocument),c=this._relativePosition,d=c?null:m.position(a);k.set(a,{left:Math.floor(b.l+(c?c.x:(b.w-
d.w)/2))+"px",top:Math.floor(b.t+(c?c.y:(b.h-d.h)/2))+"px"})}},_onKey:function(a){if(a.keyCode==y.TAB){this._getFocusItems();var b=a.target;this._firstFocusItem==this._lastFocusItem?(a.stopPropagation(),a.preventDefault()):b==this._firstFocusItem&&a.shiftKey?(f.focus(this._lastFocusItem),a.stopPropagation(),a.preventDefault()):b==this._lastFocusItem&&!a.shiftKey&&(f.focus(this._firstFocusItem),a.stopPropagation(),a.preventDefault())}else this.closable&&a.keyCode==y.ESCAPE&&(this.onCancel(),a.stopPropagation(),
a.preventDefault())},show:function(){if(this.open)return v.promise;this._started||this.startup();this._alreadyInitialized||(this._setup(),this._alreadyInitialized=!0);this._fadeOutDeferred&&(this._fadeOutDeferred.cancel(),g.hide(this));var a=n.get(this.ownerDocument);this._modalconnects.push(z(a,"scroll",e.hitch(this,"resize",null)));this._modalconnects.push(z(this.domNode,"keydown",e.hitch(this,"_onKey")));k.set(this.domNode,{opacity:0,display:""});this._set("open",!0);this._onShow();this.resize();
this._position();var b;this._fadeInDeferred=new r(e.hitch(this,function(){b.stop();delete this._fadeInDeferred}));a=this._fadeInDeferred.promise;b=x.fadeIn({node:this.domNode,duration:this.duration,beforeBegin:e.hitch(this,function(){g.show(this,this.underlayAttrs)}),onEnd:e.hitch(this,function(){this.autofocus&&g.isTop(this)&&(this._getFocusItems(),f.focus(this._firstFocusItem));this._fadeInDeferred.resolve(!0);delete this._fadeInDeferred})}).play();return a},hide:function(){if(!this._alreadyInitialized||
!this.open)return v.promise;this._fadeInDeferred&&this._fadeInDeferred.cancel();var a;this._fadeOutDeferred=new r(e.hitch(this,function(){a.stop();delete this._fadeOutDeferred}));this._fadeOutDeferred.then(e.hitch(this,"onHide"));var b=this._fadeOutDeferred.promise;a=x.fadeOut({node:this.domNode,duration:this.duration,onEnd:e.hitch(this,function(){this.domNode.style.display="none";g.hide(this);this._fadeOutDeferred.resolve(!0);delete this._fadeOutDeferred})}).play();this._scrollConnected&&(this._scrollConnected=
!1);for(var c;c=this._modalconnects.pop();)c.remove();this._relativePosition&&delete this._relativePosition;this._set("open",!1);return b},resize:function(a){if("none"!=this.domNode.style.display){this._checkIfSingleChild();if(!a){this._shrunk&&(this._singleChild&&"undefined"!=typeof this._singleChildOriginalStyle&&(this._singleChild.domNode.style.cssText=this._singleChildOriginalStyle,delete this._singleChildOriginalStyle),h.forEach([this.domNode,this.containerNode,this.titleBar,this.actionBarNode],
function(a){a&&k.set(a,{position:"static",width:"auto",height:"auto"})}),this.domNode.style.position="absolute");var b=n.getBox(this.ownerDocument);b.w*=this.maxRatio;b.h*=this.maxRatio;var c=m.position(this.domNode);c.w>=b.w||c.h>=b.h?(a={w:Math.min(c.w,b.w),h:Math.min(c.h,b.h)},this._shrunk=!0):this._shrunk=!1}a?(m.setMarginBox(this.domNode,a),b=[],this.titleBar&&b.push({domNode:this.titleBar,region:"top"}),this.actionBarNode&&b.push({domNode:this.actionBarNode,region:"bottom"}),c={domNode:this.containerNode,
region:"center"},b.push(c),a=u.marginBox2contentBox(this.domNode,a),u.layoutChildren(this.domNode,a,b),this._singleChild?(a=u.marginBox2contentBox(this.containerNode,c),this._singleChild.resize({w:a.w,h:a.h})):(this.containerNode.style.overflow="auto",this._layoutChildren())):this._layoutChildren()}},_layoutChildren:function(){h.forEach(this.getChildren(),function(a){a.resize&&a.resize()})},destroy:function(){this._fadeInDeferred&&this._fadeInDeferred.cancel();this._fadeOutDeferred&&this._fadeOutDeferred.cancel();
this._moveable&&this._moveable.destroy();for(var a;a=this._modalconnects.pop();)a.remove();g.hide(this);this.inherited(arguments)}});var l=w("dijit.Dialog",[L,p],{});l._DialogBase=p;var g=l._DialogLevelManager={_beginZIndex:950,show:function(a,b){d[d.length-1].focus=f.curNode;var c=d[d.length-1].dialog?d[d.length-1].zIndex+2:l._DialogLevelManager._beginZIndex;k.set(a.domNode,"zIndex",c);t.show(b,c-1);d.push({dialog:a,underlayAttrs:b,zIndex:c})},hide:function(a){if(d[d.length-1].dialog==a){d.pop();
var b=d[d.length-1];1==d.length?t.hide():t.show(b.underlayAttrs,b.zIndex-1);if(a.refocus){a=b.focus;if(b.dialog&&(!a||!C.isDescendant(a,b.dialog.domNode)))b.dialog._getFocusItems(),a=b.dialog._firstFocusItem;if(a)try{a.focus()}catch(c){}}}else b=h.indexOf(h.map(d,function(a){return a.dialog}),a),-1!=b&&d.splice(b,1)},isTop:function(a){return d[d.length-1].dialog==a}},d=l._dialogStack=[{dialog:null,focus:null,underlayAttrs:null}];f.watch("curNode",function(a,b,c){a=d[d.length-1].dialog;if(c&&a&&!a._fadeOutDeferred&&
c.ownerDocument==a.ownerDocument){do if(c==a.domNode||s.contains(c,"dijitPopup"))return;while(c=c.parentNode);a.focus()}});A("dijit-legacy-requires")&&E(0,function(){B(["dijit/TooltipDialog"])});return l});
/// Dialog.js.map