//>>built
define("dojo/on",["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(w,x,f){function y(a,b,c,d,e){if(d=b.match(/(.*):(.*)/))return b=d[2],d=d[1],g.selector(d,b).call(e,a,c);z.test(b)&&(c=m(c));!f("event-orientationchange")&&"orientationchange"==b&&(b="resize",a=window,c=m(c));n&&(c=n(c));if(a.addEventListener){var k=b in p,h=k?p[b]:b;a.addEventListener(h,c,k);return{remove:function(){a.removeEventListener(h,c,k)}}}if(q&&a.attachEvent)return q(a,"on"+b,c);throw Error("Target must be an event emitter");
}function A(){this.cancelable=!1;this.defaultPrevented=!0}function B(){this.bubbles=!1}var r=window.ScriptEngineMajorVersion;f.add("jscript",r&&r()+ScriptEngineMinorVersion()/10);f.add("event-orientationchange",!f("android"));f.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);f.add("event-focusin",function(a,b,c){return"onfocusin"in c});f.add("touch-can-modify-event-delegate",function(){var a=function(){};a.prototype=document.createEvent("MouseEvents");
try{var b=new a;b.target=null;return null===b.target}catch(c){return!1}});var g=function(a,b,c,d){return"function"==typeof a.on&&"function"!=typeof b&&!a.nodeType?a.on(b,c):g.parse(a,b,c,y,d,this)};g.pausable=function(a,b,c,d){var e;a=g(a,b,function(){if(!e)return c.apply(this,arguments)},d);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};g.once=function(a,b,c,d){var e=g(a,b,function(){e.remove();return c.apply(this,arguments)});return e};g.parse=function(a,b,c,d,e,k){var h;if(b.call)return b.call(k,
a,c);b instanceof Array?h=b:-1<b.indexOf(",")&&(h=b.split(/\s*,\s*/));if(h){var f=[];b=0;for(var s;s=h[b++];)f.push(g.parse(a,s,c,d,e,k));f.remove=function(){for(var a=0;a<f.length;a++)f[a].remove()};return f}return d(a,b,c,e,k)};var z=/^touch/;g.matches=function(a,b,c,d,e){e=e&&"function"==typeof e.matches?e:x.query;d=!1!==d;1!=a.nodeType&&(a=a.parentNode);for(;!e.matches(a,b,c);)if(a==c||!1===d||!(a=a.parentNode)||1!=a.nodeType)return!1;return a};g.selector=function(a,b,c){return function(d,e){function k(b){return g.matches(b,
a,d,c,f)}var f="function"==typeof a?{matches:a}:this,l=b.bubble;return l?g(d,l(k),e):g(d,b,function(a){var b=k(a.target);if(b)return a.selectorTarget=b,e.call(b,a)})}};var C=[].slice,D=g.emit=function(a,b,c){var d=C.call(arguments,2),e="on"+b;if("parentNode"in a){var f=d[0]={},g;for(g in c)f[g]=c[g];f.preventDefault=A;f.stopPropagation=B;f.target=a;f.type=b;c=f}do a[e]&&a[e].apply(a,d);while(c&&c.bubbles&&(a=a.parentNode));return c&&c.cancelable&&c},p=f("event-focusin")?{}:{focusin:"focus",focusout:"blur"};
if(!f("event-stopimmediatepropagation"))var E=function(){this.modified=this.immediatelyStopped=!0},n=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=E,a.apply(this,arguments)}};if(f("dom-addeventlistener"))g.emit=function(a,b,c){if(a.dispatchEvent&&document.createEvent){var d=(a.ownerDocument||document).createEvent("HTMLEvents");d.initEvent(b,!!c.bubbles,!!c.cancelable);for(var e in c)e in d||(d[e]=c[e]);return a.dispatchEvent(d)&&d}return D.apply(g,arguments)};
else{g._fixEvent=function(a,b){a||(a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event);if(!a)return a;try{l&&(a.type==l.type&&a.srcElement==l.target)&&(a=l)}catch(c){}if(!a.target)switch(a.target=a.srcElement,a.currentTarget=b||a.srcElement,"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=a.toElement),a.stopPropagation||(a.stopPropagation=F,a.preventDefault=G),a.type){case "keypress":var d="charCode"in a?a.charCode:a.keyCode;10==d?(d=0,a.keyCode=
13):13==d||27==d?d=0:3==d&&(d=99);a.charCode=d;d=a;d.keyChar=d.charCode?String.fromCharCode(d.charCode):"";d.charOrCode=d.keyChar||d.keyCode}return a};var l,t=function(a){this.handle=a};t.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var H=function(a){return function(b){b=g._fixEvent(b,this);var c=a.call(this,b);b.modified&&(l||setTimeout(function(){l=null}),l=b);return c}},q=function(a,b,c){c=H(c);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=
top||5.8>f("jscript"))&&!f("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var d=a[b];if(!d||!d.listeners){var e=d,d=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");d.listeners=[];a[b]=d;d.global=this;e&&d.listeners.push(_dojoIEListeners_.push(e)-1)}d.listeners.push(a=d.global._dojoIEListeners_.push(c)-
1);return new t(a)}return w.after(a,b,c,!0)},F=function(){this.cancelBubble=!0},G=g._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}var u=function(){},v=window.orientation,m=function(a){return function(b){var c=b.corrected;if(!c){var d=b.type;try{delete b.type}catch(e){}if(b.type){if(f("touch-can-modify-event-delegate"))u.prototype=b,c=new u;else{var c={},g;for(g in b)c[g]=b[g]}c.preventDefault=
function(){b.preventDefault()};c.stopPropagation=function(){b.stopPropagation()}}else c=b,c.type=d;b.corrected=c;if("resize"==d){if(v==window.orientation)return null;v=window.orientation;c.type="orientationchange";return a.call(this,c)}"rotation"in c||(c.rotation=0,c.scale=1);var d=c.changedTouches[0],h;for(h in d)delete c[h],c[h]=d[h]}return a.call(this,c)}};return g});
/// on.js.map