//>>built
define("dojo/parser","require ./_base/kernel ./_base/lang ./_base/array ./_base/config ./dom ./_base/window ./_base/url ./aspect ./promise/all ./date/stamp ./Deferred ./has ./query ./on ./ready".split(" "),function(C,y,u,x,L,M,N,O,I,P,Q,D,J,K,R,S){function E(b){return eval("("+b+")")}function T(b){var a=b._nameCaseMap,c=b.prototype;if(!a||a._extendCnt<z){var a=b._nameCaseMap={},f;for(f in c)"_"!==f.charAt(0)&&(a[f.toLowerCase()]=f);a._extendCnt=z}return a}function F(b,a){a||(a=C);var c=a._dojoParserCtorMap||
(a._dojoParserCtorMap={}),f=b.join();if(!c[f]){for(var d=[],g=0,v=b.length;g<v;g++){var m=b[g];d[d.length]=c[m]=c[m]||u.getObject(m)||~m.indexOf("/")&&a(m)}g=d.shift();c[f]=d.length?g.createSubclass?g.createSubclass(d):g.extend.apply(g,d):g}return c[f]}new Date("X");var z=0;I.after(u,"extend",function(){z++},!0);var H={_clearCache:function(){z++;_ctorMap={}},_functionFromScript:function(b,a){var c="",f="",d=b.getAttribute(a+"args")||b.getAttribute("args"),g=b.getAttribute("with"),d=(d||"").split(/\s*,\s*/);
g&&g.length&&x.forEach(g.split(/\s*,\s*/),function(a){c+="with("+a+"){";f+="}"});return new Function(d,c+b.innerHTML+f)},instantiate:function(b,a,c){a=a||{};c=c||{};var f=(c.scope||y._scopeName)+"Type",d="data-"+(c.scope||y._scopeName)+"-",g=d+"type",v=d+"mixins",m=[];x.forEach(b,function(b){var c=f in a?a[f]:b.getAttribute(g)||b.getAttribute(f);if(c){var d=b.getAttribute(v),c=d?[c].concat(d.split(/\s*,\s*/)):[c];m.push({node:b,types:c})}});return this._instantiate(m,a,c)},_instantiate:function(b,
a,c,f){function d(b){!a._started&&!c.noStart&&x.forEach(b,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return b}b=x.map(b,function(b){var d=b.ctor||F(b.types,c.contextRequire);if(!d)throw Error("Unable to resolve constructor for: '"+b.types.join()+"'");return this.construct(d,b.node,a,c,b.scripts,b.inherited)},this);return f?P(b).then(d):d(b)},construct:function(b,a,c,f,d,g){function v(a){t&&u.setObject(t,a);for(l=0;l<w.length;l++)I[w[l].advice||"after"](a,w[l].method,u.hitch(a,
w[l].func),!0);for(l=0;l<G.length;l++)G[l].call(a);for(l=0;l<A.length;l++)a.watch(A[l].prop,A[l].func);for(l=0;l<B.length;l++)R(a,B[l].event,B[l].func);return a}var m=b&&b.prototype;f=f||{};var p={};f.defaults&&u.mixin(p,f.defaults);g&&u.mixin(p,g);var r;J("dom-attributes-explicit")?r=a.attributes:J("dom-attributes-specified-flag")?r=x.filter(a.attributes,function(a){return a.specified}):(g=(/^input$|^img$/i.test(a.nodeName)?a:a.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,
"").replace(/\s*>.*$/,""),r=x.map(g.split(/\s+/),function(b){var c=b.toLowerCase();return{name:b,value:"LI"==a.nodeName&&"value"==b||"enctype"==c?a.getAttribute(c):a.getAttributeNode(c).value}}));var k=f.scope||y._scopeName;g="data-"+k+"-";var e={};"dojo"!==k&&(e[g+"props"]="data-dojo-props",e[g+"type"]="data-dojo-type",e[g+"mixins"]="data-dojo-mixins",e[k+"type"]="dojotype",e[g+"id"]="data-dojo-id");for(var l=0,h,k=[],t,q;h=r[l++];){var n=h.name,s=n.toLowerCase();h=h.value;switch(e[s]||s){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;
case "data-dojo-props":q=h;break;case "data-dojo-id":case "jsid":t=h;break;case "data-dojo-attach-point":case "dojoattachpoint":p.dojoAttachPoint=h;break;case "data-dojo-attach-event":case "dojoattachevent":p.dojoAttachEvent=h;break;case "class":p["class"]=a.className;break;case "style":p.style=a.style&&a.style.cssText;break;default:if(n in m||(n=T(b)[s]||n),n in m)switch(typeof m[n]){case "string":p[n]=h;break;case "number":p[n]=h.length?Number(h):NaN;break;case "boolean":p[n]="false"!=h.toLowerCase();
break;case "function":""===h||-1!=h.search(/[^\w\.]+/i)?p[n]=new Function(h):p[n]=u.getObject(h,!1)||new Function(h);k.push(n);break;default:s=m[n],p[n]=s&&"length"in s?h?h.split(/\s*,\s*/):[]:s instanceof Date?""==h?new Date(""):"now"==h?new Date:Q.fromISOString(h):s instanceof O?y.baseUrl+h:E(h)}else p[n]=h}}for(r=0;r<k.length;r++)e=k[r].toLowerCase(),a.removeAttribute(e),a[e]=null;if(q)try{q=E.call(f.propsThis,"{"+q+"}"),u.mixin(p,q)}catch(z){throw Error(z.toString()+" in data-dojo-props\x3d'"+
q+"'");}u.mixin(p,c);d||(d=b&&(b._noScript||m._noScript)?[]:K("\x3e script[type^\x3d'dojo/']",a));var w=[],G=[],A=[],B=[];if(d)for(l=0;l<d.length;l++)e=d[l],a.removeChild(e),c=e.getAttribute(g+"event")||e.getAttribute("event"),f=e.getAttribute(g+"prop"),q=e.getAttribute(g+"method"),k=e.getAttribute(g+"advice"),r=e.getAttribute("type"),e=this._functionFromScript(e,g),c?"dojo/connect"==r?w.push({method:c,func:e}):"dojo/on"==r?B.push({event:c,func:e}):p[c]=e:"dojo/aspect"==r?w.push({method:q,advice:k,
func:e}):"dojo/watch"==r?A.push({prop:f,func:e}):G.push(e);b=(d=b.markupFactory||m.markupFactory)?d(p,a,b):new b(p,a);return b.then?b.then(v):v(b)},scan:function(b,a){function c(a){if(!a.inherited){a.inherited={};var b=a.node,d=c(a.parent),b={dir:b.getAttribute("dir")||d.dir,lang:b.getAttribute("lang")||d.lang,textDir:b.getAttribute(r)||d.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var f=[],d=[],g={},v=(a.scope||y._scopeName)+"Type",m="data-"+(a.scope||y._scopeName)+"-",p=
m+"type",r=m+"textdir",m=m+"mixins",k=b.firstChild,e=a.inherited;if(!e){var l=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&l(a.parentNode,b)},e={dir:l(b,"dir"),lang:l(b,"lang"),textDir:l(b,r)},h;for(h in e)e[h]||delete e[h]}for(var e={inherited:e},t,q;;)if(k)if(1!=k.nodeType)k=k.nextSibling;else if(t&&"script"==k.nodeName.toLowerCase())(n=k.getAttribute("type"))&&/^dojo\/\w/i.test(n)&&t.push(k),k=k.nextSibling;else if(q)k=k.nextSibling;else{var n=k.getAttribute(p)||k.getAttribute(v);
h=k.firstChild;if(!n&&(!h||3==h.nodeType&&!h.nextSibling))k=k.nextSibling;else{q=null;if(n){var s=k.getAttribute(m);t=s?[n].concat(s.split(/\s*,\s*/)):[n];try{q=F(t,a.contextRequire)}catch(u){}q||x.forEach(t,function(a){~a.indexOf("/")&&!g[a]&&(g[a]=!0,d[d.length]=a)});s=q&&!q.prototype._noScript?[]:null;e={types:t,ctor:q,parent:e,node:k,scripts:s};e.inherited=c(e);f.push(e)}else e={node:k,scripts:t,parent:e};t=s;q=k.stopParser||q&&q.prototype.stopParser&&!a.template;k=h}}else{if(!e||!e.node)break;
k=e.node.nextSibling;q=!1;e=e.parent;t=e.scripts}var w=new D;d.length?(console.warn("WARNING: Modules being Auto-Required: "+d.join(", ")),(a.contextRequire||C)(d,function(){w.resolve(x.filter(f,function(b){if(!b.ctor)try{b.ctor=F(b.types,a.contextRequire)}catch(e){}for(var c=b.parent;c&&!c.types;)c=c.parent;var d=b.ctor&&b.ctor.prototype;b.instantiateChildren=!(d&&d.stopParser&&!a.template);b.instantiate=!c||c.instantiate&&c.instantiateChildren;return b.instantiate}))})):w.resolve(f);return w.promise},
_require:function(b,a){var c=E("{"+b.innerHTML+"}"),f=[],d=[],g=new D,v=a&&a.contextRequire||C,m;for(m in c)f.push(m),d.push(c[m]);v(d,function(){for(var a=0;a<f.length;a++)u.setObject(f[a],arguments[a]);g.resolve(arguments)});return g.promise},_scanAmd:function(b,a){var c=new D,f=c.promise;c.resolve(!0);var d=this;K("script[type\x3d'dojo/require']",b).forEach(function(b){f=f.then(function(){return d._require(b,a)});b.parentNode.removeChild(b)});return f},parse:function(b,a){b&&("string"!=typeof b&&
!("nodeType"in b))&&(a=b,b=a.rootNode);var c=b?M.byId(b):N.body();a=a||{};var f=a.template?{template:!0}:{},d=[],g=this,v=this._scanAmd(c,a).then(function(){return g.scan(c,a)}).then(function(b){return g._instantiate(b,f,a,!0)}).then(function(a){return d=d.concat(a)}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});u.mixin(d,v);return d}};y.parser=H;L.parseOnLoad&&S(100,H,"parse");return H});
/// parser.js.map