//>>built
define("dojox/mobile/_compat","dojo/_base/array dojo/_base/config dojo/_base/connect dojo/_base/fx dojo/_base/lang dojo/sniff dojo/_base/window dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/dom-attr dojo/fx dojo/fx/easing dojo/ready dojo/uacss dijit/registry dojox/fx dojox/fx/flip ./EdgeToEdgeList ./IconContainer ./ProgressIndicator ./RoundRect ./RoundRectList ./ScrollableView ./Switch ./View ./Heading require".split(" "),function(x,t,p,u,g,f,k,y,q,r,l,G,m,H,z,I,A,B,J,v,
s,C,D,n,E,K,F,L,w){var b=g.getObject("dojox.mobile",!0);if(!f("webkit")&&!(10===f("ie")||!f("ie")&&6<f("trident")))g.extend(F,{_doTransition:function(a,c,d,e){this.wakeUp(c);var b;if(!d||"none"==d)c.style.display="",a.style.display="none",c.style.left="0px",this.invokeCallback();else{if("slide"==d||"cover"==d||"reveal"==d){var h=a.offsetWidth;d=m.slideTo({node:a,duration:400,left:-h*e,top:l.get(a,"top")});b=m.slideTo({node:c,duration:400,left:0,top:l.get(c,"top")});c.style.position="absolute";c.style.left=
h*e+"px";c.style.display="";e=m.combine([d,b]);p.connect(e,"onEnd",this,function(){if(this._inProgress){a.style.display="none";a.style.left="0px";c.style.position="relative";var d=A.byNode(c);d&&!y.contains(d.domNode,"out")&&(d.containerNode.style.paddingTop="");this.invokeCallback()}})}else"slidev"==d||"coverv"==d||"reavealv"==d?(h=a.offsetHeight,d=m.slideTo({node:a,duration:400,left:0,top:-h*e}),b=m.slideTo({node:c,duration:400,left:0,top:0}),c.style.position="absolute",c.style.top=h*e+"px",c.style.left=
"0px",c.style.display="",e=m.combine([d,b]),p.connect(e,"onEnd",this,function(){this._inProgress&&(a.style.display="none",c.style.position="relative",this.invokeCallback())})):"flip"==d?(e=B.flip({node:a,dir:"right",depth:0.5,duration:400}),c.style.position="absolute",c.style.left="0px",p.connect(e,"onEnd",this,function(){this._inProgress&&(a.style.display="none",c.style.position="relative",c.style.display="",this.invokeCallback())})):(e=m.chain([u.fadeOut({node:a,duration:600}),u.fadeIn({node:c,
duration:600})]),c.style.position="absolute",c.style.left="0px",c.style.display="",l.set(c,"opacity",0),p.connect(e,"onEnd",this,function(){this._inProgress&&(a.style.display="none",c.style.position="relative",l.set(a,"opacity",1),this.invokeCallback())}));e.play()}},wakeUp:function(a){if(f("ie")&&!a._wokeup){a._wokeup=!0;var c=a.style.display;a.style.display="";for(var d=a.getElementsByTagName("*"),e=0,b=d.length;e<b;e++){var h=d[e].style.display;d[e].style.display="none";d[e].style.display="";d[e].style.display=
h}a.style.display=c}}}),g.extend(C,{scale:function(a){if(f("ie"))a={w:a,h:a},r.setMarginBox(this.domNode,a),r.setMarginBox(this.containerNode,a);else if(f("ff")){var c=a/40;l.set(this.containerNode,{MozTransform:"scale("+c+")",MozTransformOrigin:"0 0"});r.setMarginBox(this.domNode,{w:a,h:a});r.setMarginBox(this.containerNode,{w:a/c,h:a/c})}}}),f("ie")&&(g.extend(D,{buildRendering:function(){b.createRoundRect(this);this.domNode.className="mblRoundRect"}}),n._addChild=n.prototype.addChild,n._postCreate=
n.prototype.postCreate,g.extend(n,{buildRendering:function(){b.createRoundRect(this,!0);this.domNode.className="mblRoundRectList";f("ie")},postCreate:function(){n._postCreate.apply(this,arguments);this.redrawBorders()},addChild:function(a,c){n._addChild.apply(this,arguments);this.redrawBorders();b.applyPngFilter&&b.applyPngFilter(a.domNode)},redrawBorders:function(){if(!(this instanceof v))for(var a=!1,c=this.containerNode.childNodes.length-1;0<=c;c--){var d=this.containerNode.childNodes[c];"LI"==
d.tagName&&(d.style.borderBottomStyle=a?"solid":"none",a=!0)}}}),g.extend(v,{buildRendering:function(){this.domNode=this.containerNode=this.srcNodeRef||k.doc.createElement("ul");this.domNode.className="mblEdgeToEdgeList"}}),s._addChild=s.prototype.addChild,g.extend(s,{addChild:function(a,c){s._addChild.apply(this,arguments);b.applyPngFilter&&b.applyPngFilter(a.domNode)}}),g.mixin(b,{createRoundRect:function(a,c){var d,e;a.domNode=k.doc.createElement("div");a.domNode.style.padding="0px";a.domNode.style.backgroundColor=
"transparent";a.domNode.style.border="none";a.containerNode=k.doc.createElement(c?"ul":"div");a.containerNode.className="mblRoundRectContainer";if(a.srcNodeRef){a.srcNodeRef.parentNode.replaceChild(a.domNode,a.srcNodeRef);d=0;for(e=a.srcNodeRef.childNodes.length;d<e;d++)a.containerNode.appendChild(a.srcNodeRef.removeChild(a.srcNodeRef.firstChild));a.srcNodeRef=null}a.domNode.appendChild(a.containerNode);for(d=0;5>=d;d++)e=q.create("div"),e.className="mblRoundCorner mblRoundCorner"+d+"T",a.domNode.insertBefore(e,
a.containerNode),e=q.create("div"),e.className="mblRoundCorner mblRoundCorner"+d+"B",a.domNode.appendChild(e)}}),g.extend(E,{postCreate:function(){var a=q.create("div",{className:"mblDummyForIE",innerHTML:"\x26nbsp;"},this.containerNode,"first");l.set(a,{position:"relative",marginBottom:"-2px",fontSize:"1px"})}})),6>=f("ie")&&(b.applyPngFilter=function(a){a=a||k.body();a=a.getElementsByTagName("IMG");for(var c=w.toUrl("dojo/resources/blank.gif"),d=0,e=a.length;d<e;d++){var b=a[d],h=b.offsetWidth,
f=b.offsetHeight;if(0===h||0===f){if("none"!=l.get(b,"display"))continue;b.style.display="";h=b.offsetWidth;f=b.offsetHeight;b.style.display="none";if(0===h||0===f)continue}var g=b.src;-1==g.indexOf("resources/blank.gif")&&(b.src=c,b.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src\x3d'"+g+"')",b.style.width=h+"px",b.style.height=f+"px")}},!b._disableBgFilter&&b.createDomButton&&(b._createDomButton_orig=b.createDomButton,b.createDomButton=function(a,c,d){var e=b._createDomButton_orig.apply(this,
arguments);if(e&&e.className&&-1!==e.className.indexOf("mblDomButton")){var f=function(){if(e.currentStyle&&e.currentStyle.backgroundImage.match(/url.*(mblDomButton.*\.png)/)){var a=RegExp.$1,a=w.toUrl("dojox/mobile/themes/common/domButtons/compat/")+a;e.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src\x3d'"+a+"',sizingMethod\x3d'crop')";e.style.background="none"}};setTimeout(f,1E3);setTimeout(f,5E3)}return e})),b.loadCssFile=function(a){b.loadedCssFiles||(b.loadedCssFiles=
[]);k.doc.createStyleSheet?setTimeout(function(a){return function(){var d=k.doc.createStyleSheet(a);d&&b.loadedCssFiles.push(d.owningElement)}}(a),0):b.loadedCssFiles.push(q.create("link",{href:a,type:"text/css",rel:"stylesheet"},k.doc.getElementsByTagName("head")[0]))},b.loadCss=function(a){if(!b._loadedCss){var c={};x.forEach(b.getCssPaths(),function(a){c[a]=!0});b._loadedCss=c}g.isArray(a)||(a=[a]);for(var d=0;d<a.length;d++){var e=a[d];b._loadedCss[e]||(b._loadedCss[e]=!0,b.loadCssFile(e))}},
b.getCssPaths=function(){var a=[],c,d,b=k.doc.styleSheets;for(c=0;c<b.length;c++)if(!b[c].href){var f=b[c].cssRules||b[c].imports;if(f)for(d=0;d<f.length;d++)f[d].href&&a.push(f[d].href)}b=k.doc.getElementsByTagName("link");c=0;for(d=b.length;c<d;c++)b[c].href&&a.push(b[c].href);return a},b.loadCompatPattern=/\/mobile\/themes\/.*\.css$/,b.loadCompatCssFiles=function(a){if(f("ie")&&!a)setTimeout(function(){b.loadCompatCssFiles(!0)},0);else{b._loadedCss=void 0;a=b.getCssPaths();for(var c=0;c<a.length;c++){var d=
a[c];if((d.match(t.mblLoadCompatPattern||b.loadCompatPattern)||-1!==location.href.indexOf("mobile/tests/"))&&-1===d.indexOf("-compat.css"))d=d.substring(0,d.length-4)+"-compat.css",b.loadCss(d)}}},b.hideAddressBar=function(a,c){!1!==c&&b.resizeAll()},z(function(){!1!==t.mblLoadCompatCssFiles&&b.loadCompatCssFiles();b.applyPngFilter&&b.applyPngFilter()});return b});
/// _compat.js.map