//>>built
define("dojox/charting/plot2d/Indicator","dojo/_base/lang dojo/_base/array dojo/_base/declare ./CartesianBase ./_PlotEvents ./common ../axis2d/common dojox/gfx dojox/lang/utils dojox/gfx/fx dojo/has".split(" "),function(t,E,G,H,I,s,J,v,F,K,M){var L=function(b,c){var d=b.declaredClass,a;if(-1!=d.indexOf("svg"))try{return t.mixin({},b.rawNode.getBBox())}catch(e){}else{if(-1!=d.indexOf("vml")){var f=b.rawNode,s=f.style.display;f.style.display="inline";d=v.pt2px(parseFloat(f.currentStyle.width));a=v.pt2px(parseFloat(f.currentStyle.height));
d={x:0,y:0,width:d,height:a};y(b,d);f.style.display=s;return d}if(-1!=d.indexOf("silverlight"))return y(b,{width:b.rawNode.actualWidth,height:b.rawNode.actualHeight},0.75);if(b.getTextWidth)return d=b.getTextWidth(),f=b.getFont(),a=v.normalizedLength(f?f.size:v.defaultFont.size),d={width:d,height:a},y(b,d,0.75),d}return null},y=function(b,c,d){var a=c.width,e=c.height;b=b.getShape();switch(b.align){case "end":c.x=b.x-a;break;case "middle":c.x=b.x-a/2;break;default:c.x=b.x}c.y=b.y-e*(d||1);return c};
return G("dojox.charting.plot2d.Indicator",[H,I],{defaultParams:{vertical:!0,fixed:!0,precision:0,lines:!0,labels:"line",markers:!0},optionalParams:{lineStroke:{},outlineStroke:{},shadowStroke:{},lineFill:{},stroke:{},outline:{},shadow:{},fill:{},fillFunc:null,labelFunc:null,font:"",fontColor:"",markerStroke:{},markerOutline:{},markerShadow:{},markerFill:{},markerSymbol:"",values:[],offset:{},start:!1,animate:!1},constructor:function(b,c){this.opt=t.clone(this.defaultParams);F.updateWithObject(this.opt,
c);"number"==typeof c.values&&(c.values=[c.values]);F.updateWithPattern(this.opt,c,this.optionalParams);this.animate=this.opt.animate},render:function(b,c){if(this.zoom)return this.performZoom(b,c);if(!this.isDirty())return this;this.cleanGroup(null,!0);if(!this.opt.values)return this;this._updateIndicator();return this},_updateIndicator:function(){var b=this.chart.theme,c=this._hAxis.name,d=this._vAxis.name,a=this._hAxis.getScaler().bounds,e=this._vAxis.getScaler().bounds,f={};f[c]=a.from;f[d]=e.from;
var t=this.toPage(f);f[c]=a.to;f[d]=e.to;var B=this.toPage(f),l=this.events(),a=E.map(this.opt.values,function(a,b){return this._renderIndicator(a,b,c,d,t,B,l,this.animate)},this),e=a.length;if("trend"==this.opt.labels){var f=this.opt.vertical,g=this._data[0][0],k=this._data[e-1][0]-g,g=this.opt.labelFunc?this.opt.labelFunc(-1,this.values,this._data,this.opt.fixed,this.opt.precision):s.getLabel(k,this.opt.fixed,this.opt.precision)+" ("+s.getLabel(100*k/g,!0,2)+"%)";this._renderText(this.getGroup(),
g,this.chart.theme,f?(a[0].x+a[e-1].x)/2:a[1].x,f?a[0].y:(a[1].y+a[e-1].y)/2,-1,this.opt.values,this._data)}if((b=void 0!=this.opt.lineFill?this.opt.lineFill:b.indicator.lineFill)&&1<e)f=Math.min(a[0].x1,a[e-1].x1),g=Math.min(a[0].y1,a[e-1].y1),this.getGroup().createRect({x:f,y:g,width:Math.max(a[0].x2,a[e-1].x2)-f,height:Math.max(a[0].y2,a[e-1].y2)-g}).setFill(b).moveToBack()},_renderIndicator:function(b,c,d,a,e,f,v,B){var l=this.chart.theme,g=this.chart.getCoords(),k=this.opt.vertical,u=this.getGroup().createGroup(),
h={};h[d]=k?b:0;h[a]=k?0:b;var h=this.toPage(h),q=k?h.x>=e.x&&h.x<=f.x:h.y>=f.y&&h.y<=e.y,C=h.x-g.x,D=h.y-g.y,m=k?C:e.x-g.x,n=k?e.y-g.y:D,z=k?m:f.x-g.x,w=k?f.y-g.y:n;if(this.opt.lines&&q){var r=this.opt.hasOwnProperty("lineShadow")?this.opt.lineShadow:l.indicator.lineShadow,x=this.opt.hasOwnProperty("lineStroke")?this.opt.lineStroke:l.indicator.lineStroke,p=this.opt.hasOwnProperty("lineOutline")?this.opt.lineOutline:l.indicator.lineOutline;r&&u.createLine({x1:m+r.dx,y1:n+r.dy,x2:z+r.dx,y2:w+r.dy}).setStroke(r);
p&&(p=s.makeStroke(p),p.width=2*p.width+(x?x.width:0),u.createLine({x1:m,y1:n,x2:z,y2:w}).setStroke(p));u.createLine({x1:m,y1:n,x2:z,y2:w}).setStroke(x)}var y;if(this.opt.markers&&q){var A=this._data[c];A&&(y=E.map(A,function(c,q){h[d]=k?b:c;h[a]=k?c:b;h=this.toPage(h);if(k?h.y<=e.y&&h.y>=f.y:h.x>=e.x&&h.x<=f.x){C=h.x-g.x;D=h.y-g.y;var m=this.opt.markerSymbol?this.opt.markerSymbol:l.indicator.markerSymbol,n="M"+C+" "+D+" "+m;r=void 0!=this.opt.markerShadow?this.opt.markerShadow:l.indicator.markerShadow;
x=void 0!=this.opt.markerStroke?this.opt.markerStroke:l.indicator.markerStroke;p=void 0!=this.opt.markerOutline?this.opt.markerOutline:l.indicator.markerOutline;r&&u.createPath("M"+(C+r.dx)+" "+(D+r.dy)+" "+m).setFill(r.color).setStroke(r);p&&(p=s.makeStroke(p),p.width=2*p.width+(x?x.width:0),u.createPath(n).setStroke(p));m=u.createPath(n);n=this._shapeFill(void 0!=this.opt.markerFill?this.opt.markerFill:l.indicator.markerFill,m.getBoundingBox());m.setFill(n).setStroke(x)}return c},this))}A=this.opt.start?
{x:m,y:k?n:w}:{x:k?m:z,y:k?w:n};this.opt.labels&&("trend"!=this.opt.labels&&q)&&(this.opt.labelFunc?q=this.opt.labelFunc(c,this.opt.values,this._data,this.opt.fixed,this.opt.precision,this.opt.labels):"markers"==this.opt.labels?(q=E.map(y,function(a){return s.getLabel(a,this.opt.fixed,this.opt.precision)},this),q=1!=q.length?"[ "+q.join(", ")+" ]":q[0]):q=s.getLabel(b,this.opt.fixed,this.opt.precision),this._renderText(u,q,l,A.x,A.y,c,this.opt.values,this._data));v&&this._connectEvents({element:"indicator",
run:this.run?this.run[c]:void 0,shape:u,value:b});B&&this._animateIndicator(u,k,k?n:m,k?n+w:m+z,B);return t.mixin(A,{x1:m,y1:n,x2:z,y2:w})},_animateIndicator:function(b,c,d,a,e){K.animateTransform(t.delegate({shape:b,duration:1200,transform:[{name:"translate",start:c?[0,d]:[d,0],end:[0,0]},{name:"scale",start:c?[1,1/a]:[1/a,1],end:[1,1]},{name:"original"}]},e)).play()},clear:function(){this.inherited(arguments);this._data=[]},addSeries:function(b){this.inherited(arguments);this._data.push(b.data)},
_renderText:function(b,c,d,a,e,f,t,v){this.opt.offset&&(a+=this.opt.offset.x,e+=this.opt.offset.y);c=J.createText.gfx(this.chart,b,a,e,"middle",c,this.opt.font?this.opt.font:d.indicator.font,this.opt.fontColor?this.opt.fontColor:d.indicator.fontColor);a=L(c,c.getShape().text);a.x-=2;a.y-=1;a.width+=4;a.height+=2;a.r=this.opt.radius?this.opt.radius:d.indicator.radius;var l=void 0!=this.opt.shadow?this.opt.shadow:d.indicator.shadow;e=void 0!=this.opt.stroke?this.opt.stroke:d.indicator.stroke;var g=
void 0!=this.opt.outline?this.opt.outline:d.indicator.outline;l&&b.createRect(a).setFill(l.color).setStroke(l);g&&(g=s.makeStroke(g),g.width=2*g.width+(e?e.width:0),b.createRect(a).setStroke(g));d=this.opt.fillFunc?this.opt.fillFunc(f,t,v):void 0!=this.opt.fill?this.opt.fill:d.indicator.fill;b.createRect(a).setFill(this._shapeFill(d,a)).setStroke(e);c.moveToFront()},getSeriesStats:function(){return t.delegate(s.defaultStats)}})});
/// Indicator.js.map