//>>built
define("dojox/charting/plot2d/Pie","dojo/_base/lang dojo/_base/array dojo/_base/declare ./Base ./_PlotEvents ./common dojox/gfx dojox/gfx/matrix dojox/lang/functional dojox/lang/utils dojo/has".split(" "),function(D,n,E,H,L,M,v,K,k,F,N){return E("dojox.charting.plot2d.Pie",[H,L],{defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:20,labelStyle:"default",htmlLabels:!0,radGrad:"native",fanSize:5,startAngle:0},optionalParams:{radius:0,omitLabels:!1,stroke:{},outline:{},shadow:{},fill:{},
filter:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},constructor:function(g,d){this.opt=D.clone(this.defaultParams);F.updateWithObject(this.opt,d);F.updateWithPattern(this.opt,d,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);this.dyn=[];this.run=null;return this},setAxis:function(g){return this},addSeries:function(g){this.run=g;return this},getSeriesStats:function(){return D.delegate(M.defaultStats)},getRequiredColors:function(){return this.run?
this.run.data.length:0},render:function(g,d){if(!this.dirty)return this;this.resetEvents();this.dirty=!1;this._eventSeries={};this.cleanGroup();var q=this.group,b=this.chart.theme;if(!this.run||!this.run.data.length)return this;var c=(g.width-d.l-d.r)/2,e=(g.height-d.t-d.b)/2,h=Math.min(c,e),x="font"in this.opt?this.opt.font:b.series.font,w,B=K._degToRad(this.opt.startAngle),m=B,l,t,u,C,F=this.events(),y=n.map(this.run.data,function(a,b){"number"!=typeof a&&a.hidden&&(this.runFilter.push(b),a.hidden=
!1);return n.some(this.runFilter,function(a){return a==b})?"number"==typeof a?0:{y:0,text:a.text}:a},this);this.dyn=[];"radius"in this.opt&&(h=this.opt.radius,C=h-this.opt.labelOffset);var a={cx:d.l+c,cy:d.t+e,r:h};if(this.opt.shadow||b.shadow){l=this.opt.shadow||b.shadow;var z=D.clone(a);z.cx+=l.dx;z.cy+=l.dy;q.createCircle(z).setFill(l.color).setStroke(l)}if(q.setFilter&&(this.opt.filter||b.filter))q.createCircle(a).setFill(b.series.stroke).setFilter(this.opt.filter||b.filter);if("number"==typeof y[0]){l=
k.map(y,"x ? Math.max(x, 0) : 0");if(k.every(l,"\x3c\x3d 0"))return q.createCircle(a).setStroke(b.series.stroke),this.dyn=n.map(l,function(){return{}}),this;t=k.map(l,"/this",k.foldl(l,"+",0));this.opt.labels&&(u=n.map(t,function(a){return 0<a?this._getLabel(100*a)+"%":""},this))}else{l=k.map(y,"x ? Math.max(x.y, 0) : 0");if(k.every(l,"\x3c\x3d 0"))return q.createCircle(a).setStroke(b.series.stroke),this.dyn=n.map(l,function(){return{}}),this;t=k.map(l,"/this",k.foldl(l,"+",0));this.opt.labels&&(u=
n.map(t,function(a,b){if(0>a)return"";var d=y[b];return"text"in d?d.text:this._getLabel(100*a)+"%"},this))}var G=k.map(y,function(a,d){var p=[this.opt,this.run];null!==a&&"number"!=typeof a&&p.push(a);this.opt.styleFunc&&p.push(this.opt.styleFunc(a));return b.next("slice",p,!0)},this);this.opt.labels&&(w=x?v.normalizedLength(v.splitFontString(x).size):0,l=k.foldl1(k.map(u,function(a,b){return v._base._getTextBox(a,{font:G[b].series.font}).w},this),"Math.max(a, b)")/2,0>this.opt.labelOffset&&(h=Math.min(c-
2*l,e-w)+this.opt.labelOffset),C=h-this.opt.labelOffset);var I=Array(t.length);n.some(t,function(b,c){if(0>b)return!1;var p=y[c],r=G[c],f;if(0==b)return this.dyn.push({fill:r.series.fill,stroke:r.series.stroke}),!1;if(1<=b){f=this._plotFill(r.series.fill,g,d);f=this._shapeFill(f,{x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r});f=this._pseudoRadialFill(f,{x:a.cx,y:a.cy},a.r);var e=q.createCircle(a).setFill(f).setStroke(r.series.stroke);this.dyn.push({fill:f,stroke:r.series.stroke});F&&(p={element:"slice",
index:c,run:this.run,shape:e,x:c,y:"number"==typeof p?p:p.y,cx:a.cx,cy:a.cy,cr:h},this._connectEvents(p),I[c]=p);return!1}var l=m+2*b*Math.PI;c+1==t.length&&(l=B+2*Math.PI);var e=l-m,k=a.cx+h*Math.cos(m),n=a.cy+h*Math.sin(m),x=a.cx+h*Math.cos(l),w=a.cy+h*Math.sin(l);f=K._degToRad(this.opt.fanSize);if(r.series.fill&&"radial"===r.series.fill.type&&"fan"===this.opt.radGrad&&e>f){var u=q.createGroup(),v=Math.ceil(e/f),A=e/v;f=this._shapeFill(r.series.fill,{x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r});
for(var s=0;s<v;++s){var z=0==s?k:a.cx+h*Math.cos(m+(s-0.2)*A),C=0==s?n:a.cy+h*Math.sin(m+(s-0.2)*A),D=s==v-1?x:a.cx+h*Math.cos(m+(s+1+0.2)*A),E=s==v-1?w:a.cy+h*Math.sin(m+(s+1+0.2)*A);u.createPath().moveTo(a.cx,a.cy).lineTo(z,C).arcTo(h,h,0,A>Math.PI,!0,D,E).lineTo(a.cx,a.cy).closePath().setFill(this._pseudoRadialFill(f,{x:a.cx,y:a.cy},h,m+(s+0.5)*A,m+(s+0.5)*A))}u.createPath().moveTo(a.cx,a.cy).lineTo(k,n).arcTo(h,h,0,e>Math.PI,!0,x,w).lineTo(a.cx,a.cy).closePath().setStroke(r.series.stroke);e=
u}else e=q.createPath().moveTo(a.cx,a.cy).lineTo(k,n).arcTo(h,h,0,e>Math.PI,!0,x,w).lineTo(a.cx,a.cy).closePath().setStroke(r.series.stroke),(f=r.series.fill)&&"radial"===f.type?(f=this._shapeFill(f,{x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r}),"linear"===this.opt.radGrad&&(f=this._pseudoRadialFill(f,{x:a.cx,y:a.cy},h,m,l))):f&&"linear"===f.type&&(f=this._plotFill(f,g,d),f=this._shapeFill(f,e.getBoundingBox())),e.setFill(f);this.dyn.push({fill:f,stroke:r.series.stroke});F&&(p={element:"slice",
index:c,run:this.run,shape:e,x:c,y:"number"==typeof p?p:p.y,cx:a.cx,cy:a.cy,cr:h},this._connectEvents(p),I[c]=p);m=l;return!1},this);if(this.opt.labels)if("default"==this.opt.labelStyle)m=B,n.some(t,function(b,c){if(0>=b)return!1;var d=G[c];if(1<=b)return this.renderLabel(q,a.cx,a.cy+w/2,u[c],d,0<this.opt.labelOffset),!0;var e=m+2*b*Math.PI;c+1==t.length&&(e=B+2*Math.PI);if(this.opt.omitLabels&&0.001>e-m)return!1;var f=(m+e)/2,g=a.cx+C*Math.cos(f),f=a.cy+C*Math.sin(f)+w/2;this.renderLabel(q,g,f,u[c],
d,0<this.opt.labelOffset);m=e;return!1},this);else if("columns"==this.opt.labelStyle){var m=B,E=this.opt.omitLabels,J=[];n.forEach(t,function(a,b){var c=m+2*a*Math.PI;b+1==t.length&&(c=B+2*Math.PI);var d=(m+c)/2;J.push({angle:d,left:0>Math.cos(d),theme:G[b],index:b,omit:E?0.001>c-m:!1});m=c});c=v._base._getTextBox("a",{font:x}).h;this._getProperLabelRadius(J,c,1.1*a.r);n.forEach(J,function(b,c){if(!b.omit){var d=a.cx-2*a.r,e=a.cx+2*a.r,f=v._base._getTextBox(u[c],{font:b.theme.series.font}).w,g=a.cx+
b.labelR*Math.cos(b.angle),h=a.cy+b.labelR*Math.sin(b.angle),e=b.left?d+f:e-f,d=b.left?d:e,l=q.createPath().moveTo(a.cx+a.r*Math.cos(b.angle),a.cy+a.r*Math.sin(b.angle));Math.abs(b.labelR*Math.cos(b.angle))<2*a.r-f&&l.lineTo(g,h);l.lineTo(e,h).setStroke(b.theme.series.labelWiring);this.renderLabel(q,d,h,u[c],b.theme,!1,"left")}},this)}var H=0;this._eventSeries[this.run.name]=k.map(y,function(a){return 0>=a?null:I[H++]});return this},_getProperLabelRadius:function(g,d,q){var b,c,e=1,h=1;if(1==g.length)g[0].labelR=
q;else{for(var k=0;k<g.length;k++){var n=Math.abs(Math.sin(g[k].angle));g[k].left?e>=n&&(e=n,b=g[k]):h>=n&&(h=n,c=g[k])}b.labelR=c.labelR=q;this._calculateLabelR(b,g,d);this._calculateLabelR(c,g,d)}},_calculateLabelR:function(g,d,k){for(var b=g.index,c=d.length,e=g.labelR;!(d[b%c].left^d[(b+1)%c].left);)d[(b+1)%c].omit||(e=(Math.sin(d[b%c].angle)*e+(d[b%c].left?-k:k))/Math.sin(d[(b+1)%c].angle),e=e<g.labelR?g.labelR:e,d[(b+1)%c].labelR=e),b++;b=g.index;for(c=0==b?c-1:b-1;!(d[b].left^d[c].left);)d[c].omit||
(e=(Math.sin(d[b].angle)*e+(d[b].left?k:-k))/Math.sin(d[c].angle),e=e<g.labelR?g.labelR:e,d[c].labelR=e),b--,c--,b=0>b?b+d.length:b,c=0>c?c+d.length:c}})});
/// Pie.js.map